import { getAdminAuth, getAdminFirestore } from '../../../src/security/firebaseAdmin.js';
import { CAREER_DATA } from '../../../src/data/careers.js';
import { ASSESSMENT_VERSION } from '../../../src/career/careerAssessmentBlueprint.js';
import { resolveBundle, getItemsForBundle } from '../../../src/career/assessmentSelection.js';
import { matchCareerToSelectedProfile, scoreSelectedAssessment } from '../../../src/career/scoreSelectedAssessment.js';
import { buildCareerDecisionResult } from '../../../src/career/careerDecisionContract.js';
import { buildDecisionSupportCoverage } from '../../../src/career/decisionSupportCoverage.js';
import { PREMIUM_REPORT_PAGE_COUNT, FREE_REPORT_PAGE_COUNT } from '../../../src/career/reportArchitecture.js';
function bearerToken(req){const h=req.headers.authorization||req.headers.Authorization;if(typeof h!=='string')return null;const m=h.match(/^Bearer\s+(.+)$/i);return m?m[1]:null;}
function safeObject(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}
function safeString(v,max=300){return String(v||'').trim().slice(0,max);}
function buildCareerMatches(scored,intake){return CAREER_DATA.map(c=>buildCareerDecisionResult(c,intake,matchCareerToSelectedProfile(c,scored))).sort((a,b)=>(b.interestAlignmentIndex??-1)-(a.interestAlignmentIndex??-1)).slice(0,12);}
export default async function handler(req,res){
 if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'Method not allowed.'});}
 const token=bearerToken(req);if(!token)return res.status(401).json({error:'Authentication required.'});
 let decoded;try{decoded=await getAdminAuth().verifyIdToken(token);}catch(_){return res.status(401).json({error:'Invalid or expired authentication token.'});}
 const body=req.body||{},pathway=['student','working_professional','hr_role_alignment'].includes(body.pathway)?body.pathway:'student',intake=safeObject(body.intake),answers=safeObject(body.answers),db=getAdminFirestore();let userData={};try{const s=await db.collection('users').doc(decoded.uid).get();userData=s.exists?s.data():{};}catch(_){ }
 const requestedCode=safeString(intake.licenseCode||userData.institutionAccessCode,120);let institutionEntitled=false,institutionCodeRecord=null;if(requestedCode){try{const s=await db.collection('institutionCodes').doc(requestedCode).get();if(s.exists){institutionCodeRecord=s.data();institutionEntitled=s.data()?.status==='redeemed'&&s.data()?.redeemedBy===decoded.uid;}}catch(_){}}
 const institutionBundleId=institutionEntitled?safeString(institutionCodeRecord?.bundleId,160):'',requestedBundleId=safeString(body.bundleId,160),entitlement=userData.careerReportAccess||null,entitlementBundleId=safeString(entitlement?.bundleId||userData.careerAssessmentBundleId,160),bundle=resolveBundle(institutionBundleId||requestedBundleId||entitlementBundleId),items=getItemsForBundle(bundle.id),scored=scoreSelectedAssessment(answers,{bundleId:bundle.id}),matches=buildCareerMatches(scored,intake),reportTier=institutionEntitled?'institution':entitlement?.status==='paid'?'premium':'free',premiumAccess=reportTier!=='free',guidanceIncluded=bundle.familyCount===5,guidanceAssessed=guidanceIncluded&&(scored.readinessPercent!=null||scored.adaptabilityPercent!=null||(scored.environment&&Object.keys(scored.environment).length>0));
 const report={version:ASSESSMENT_VERSION,pathway,bundleId:bundle.id,bundleSku:bundle.sku,bundleTitle:bundle.title,selectedFamilyIds:bundle.familyIds,selectedTestCount:bundle.familyCount,deliveryMode:bundle.deliveryMode,estimatedMinutes:bundle.durationMinutes,questionCount:items.length,reportPages:premiumAccess?PREMIUM_REPORT_PAGE_COUNT:FREE_REPORT_PAGE_COUNT,reportType:premiumAccess?'full_career_intelligence':'career_snapshot',reportTier,embeddedGuidanceLayer:guidanceIncluded?{included:true,assessed:guidanceAssessed,domains:['career_decision_readiness','work_environment','adaptability_resilience']}:{included:false,assessed:false,domains:[]},careerMatching:{method:'riasec_interest_alignment_v1',scoreLabel:'Interest Alignment Index',limitations:['Career-side validated norms for Big Five, values, reasoning, skills, learning, academic performance, readiness, environment and adaptability are not currently available; those domains are therefore excluded from ranking.']},completedAt:new Date().toISOString(),intake:{dob:safeString(intake.dob,30),age:Number.isFinite(Number(intake.age))?Number(intake.age):null,ageBand:safeString(intake.ageBand,30),educationStage:safeString(intake.educationStage,80),board:safeString(intake.board,100),className:safeString(intake.className,100),stream:safeString(intake.stream,100),institutionName:safeString(intake.institutionName||userData.institutionName,160),likedSubjects:Array.isArray(intake.likedSubjects)?intake.likedSubjects.slice(0,30):[],dislikedSubjects:Array.isArray(intake.dislikedSubjects)?intake.dislikedSubjects.slice(0,30):[],hobbies:safeString(intake.hobbies,500),curiosity:safeString(intake.curiosity,500),goal:safeString(intake.goal,500),currentRole:safeString(intake.currentRole,160),professionalIntent:safeString(intake.professionalIntent,80),academicAverage:Number(intake.academicAverage||0)},scores:scored,careerExploration:matches,decisionSupportCoverage:null,reflection:{statement:'Results are a structured starting point for exploration, not a verdict about the person.',recommendedNextStep:pathway==='working_professional'?'Review the available stay/grow, lateral pivot and industry pivot pathways with a career professional.':'Explore at least three pathways and compare their education, work, skills and lived experience before deciding.'}};
 report.decisionSupportCoverage=buildDecisionSupportCoverage(report);
 try{await db.collection('users').doc(decoded.uid).set({careerAssessmentV2:report,careerAssessment:{version:ASSESSMENT_VERSION,completedAt:report.completedAt,bundleId:bundle.id,bundleSku:bundle.sku,selectedFamilyIds:bundle.familyIds,hollandCode:scored.riasecCode?scored.riasecCode.split('').slice(0,3):[],riasecScores:scored.riasec||null,top5Careers:matches.slice(0,5).map(c=>({name:c.name,stream:c.pathway.listedStreams.join(' / '),matchScore:c.interestAlignmentIndex,scoreLabel:c.scoreLabel,tags:c.decisionProfile.fit.interestProfile}))},assessmentCompletedAt:report.completedAt,riasecCode:scored.riasecCode||null,riasecScores:scored.riasec||null,careerAssessmentFamilies:bundle.familyIds,careerAssessmentBundleId:bundle.id,careerAssessmentReportTier:reportTier,careerAssessmentReportPages:report.reportPages,careerAssessmentQuestionCount:report.questionCount,careerAssessmentEmbeddedGuidance:report.embeddedGuidanceLayer},{merge:true});if(institutionEntitled&&institutionCodeRecord?.institutionId&&institutionCodeRecord?.rosterId)await db.collection('institutions').doc(institutionCodeRecord.institutionId).collection('roster').doc(institutionCodeRecord.rosterId).set({assessmentStatus:'completed',reportStatus:'ready',bundleId:bundle.id,bundleSku:bundle.sku,selectedFamilyIds:bundle.familyIds,reportPages:report.reportPages,questionCount:report.questionCount,reportTier,embeddedGuidanceLayer:report.embeddedGuidanceLayer,updatedAt:report.completedAt,claimedBy:decoded.uid,claimedAt:institutionCodeRecord.redeemedAt||null},{merge:true});return res.status(200).json({saved:true,report});}catch(error){console.error('[career/submit-v2] failed:',error?.message||error);return res.status(500).json({error:'Unable to save the career assessment.'});}
}
