import React,{useMemo} from 'react';
import {STUDENT_PREMIUM_REPORT} from '../career/reportArchitecture';

const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:20,boxShadow:'0 8px 28px rgba(15,23,42,.05)'};
const aliases={executive_snapshot:['executiveSnapshot','snapshot'],interest_personality:['interestPersonality','interests','personality'],strengths_values:['strengthsValues','strengths'],developmental_context:['developmentalContext','academicContext'],riasec_profile:['riasec','riasecProfile'],personality_profile:['big5','personalityProfile'],career_values:['values','careerValues'],reasoning_profile:['reasoning','reasoningProfile'],decision_readiness:['readiness','decisionReadiness'],adaptability:['adaptability','resilience'],work_environment:['workEnvironment','preferredWorkEnvironment'],career_directions:['careerExploration','careerDirections'],top_career_directions:['topCareerDirections'],alternative_careers:['alternativeCareers','alternatives'],pathway_analysis:['pathwayAnalysis','pathways'],stream_analysis:['streamAnalysis','streamScenarios'],education_roadmap:['educationRoadmap','education'],skills_evidence:['skillsEvidence','skillsPlan'],affordability:['affordability','friction'],action_roadmap:['actionRoadmap','actionPlan'],counsellor_review:['counsellorReview','limitations']};
function valueAt(report,id){const keys=aliases[id]||[id];for(const key of keys){if(report?.[key]!==undefined&&report?.[key]!==null)return report[key];if(report?.sections?.[key]!==undefined&&report?.sections?.[key]!==null)return report.sections[key];}return undefined;}
function state(value){if(value===undefined||value===null)return ['Not available','missing'];if(Array.isArray(value)&&value.length===0)return ['Not available','missing'];if(typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===0)return ['Not available','missing'];return ['Available','available'];}
export default function InstitutionCareerReportCoverage({report={}}){
 const rows=useMemo(()=>STUDENT_PREMIUM_REPORT.map(section=>{const [label,status]=state(valueAt(report,section.id));return {...section,status:label,tone:status};}),[report]);
 const available=rows.filter(x=>x.tone==='available').length;
 return <section style={{...card,marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'baseline',flexWrap:'wrap'}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:1.2,color:'#4338ca'}}>REPORT COVERAGE</div><h2 style={{margin:'5px 0'}}>Student report → institutional reflection</h2><p style={{margin:0,color:'#64748b',fontSize:13}}>Every premium student-report section is explicitly tracked. Missing data is shown as unavailable rather than inferred.</p></div><div style={{fontWeight:950,color:'#0f172a'}}>{available}/{rows.length} available</div></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:8,marginTop:14}}>{rows.map((r,i)=><div key={r.id} style={{padding:12,border:'1px solid #eef2f7',borderRadius:12,background:r.tone==='available'?'#f0fdf4':'#f8fafc'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><span style={{fontWeight:900,fontSize:13}}>{i+1}. {r.title}</span><span style={{fontSize:11,fontWeight:900,color:r.tone==='available'?'#15803d':'#64748b'}}>{r.status}</span></div><div style={{marginTop:4,fontSize:11,color:'#64748b'}}>{r.purpose}</div></div>)}</div></section>;
}
