import React,{useEffect,useMemo,useState} from 'react';
import {auth} from '../firebase';

const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:22,boxShadow:'0 8px 28px rgba(15,23,42,.05)'};
const input={width:'100%',padding:'12px 13px',border:'1px solid #dbe3ef',borderRadius:10,fontSize:13,outline:'none'};
const normaliseHeader=(v)=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function mapRows(raw){if(!Array.isArray(raw)||!raw.length)return[];const headers=raw[0].map(normaliseHeader);const find=(names)=>{const i=headers.findIndex(h=>names.includes(h));return i>=0?i:null;};const name=find(['fullname','studentname','name','student']);const cls=find(['class','grade','classname','standard']);const sec=find(['section','division']);const roll=find(['rollnumber','rollno','roll']);return raw.slice(1).map((r)=>({fullName:name!=null?String(r[name]||'').trim():'',className:cls!=null?String(r[cls]||'').trim():'',section:sec!=null?String(r[sec]||'').trim():'',rollNumber:roll!=null?String(r[roll]||'').trim():''})).filter(x=>x.fullName);}

export default function InstitutionCareerDashboard(){
 const [institution,setInstitution]=useState(null);const [students,setStudents]=useState([]);const [summary,setSummary]=useState({});const [fileName,setFileName]=useState('');const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [uploading,setUploading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [revealed,setRevealed]=useState({});const [institutionName,setInstitutionName]=useState('');const [licenseCount,setLicenseCount]=useState('150');const [selectedReport,setSelectedReport]=useState(null);
 const user=auth.currentUser;
 const founder=user?.email?.toLowerCase()==='antonio.antonio.noronha@gmail.com';
 const load=async(id='')=>{try{const token=await auth.currentUser?.getIdToken();if(!token)return;const url=id?`/api/institution/dashboard?institutionId=${encodeURIComponent(id)}`:'/api/institution/dashboard';const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to load institution dashboard.');setInstitution(d.institution);setStudents(d.students||[]);setSummary(d.summary||{});setInstitutionName(d.institution?.name||'');}catch(e){if(!founder)setError(e.message||'Unable to load institution.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const available=Number(institution?.licenses?.available||0);
 const parseFile=async(file)=>{setError('');setMessage('');setFileName(file.name);try{const ext=file.name.toLowerCase().split('.').pop();if(ext==='csv'){const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const parsed=lines.map(line=>line.split(',').map(v=>v.trim().replace(/^"|"$/g,'')));setRows(mapRows(parsed));return;}if(ext==='xlsx'||ext==='xls'){const XLSX=await import('xlsx');const buffer=await file.arrayBuffer();const wb=XLSX.read(buffer,{type:'array'});const sheet=wb.Sheets[wb.SheetNames[0]];const parsed=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});setRows(mapRows(parsed));return;}if(ext==='docx'){const mammoth=await import('mammoth');const buffer=await file.arrayBuffer();const result=await mammoth.extractRawText({arrayBuffer:buffer});const lines=result.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const parsed=lines.map(line=>line.includes('\t')?line.split('\t'):line.split(/\s{2,}/));setRows(mapRows(parsed));return;}throw new Error('Supported formats are CSV, Excel (.xlsx/.xls) and Word (.docx).');}catch(e){setRows([]);setError(e.message||'Unable to read this roster file.');}};
 const provision=async()=>{setError('');setMessage('');if(!rows.length){setError('Please upload a roster first.');return;}if(founder&&!institutionName.trim()){setError('Enter the institution name.');return;}if(founder&&Number(licenseCount)<rows.length){setError(`You are uploading ${rows.length} students but only ${licenseCount} licenses were allocated.`);return;}if(!founder&&rows.length>available){setError(`Only ${available} licenses remain.`);return;}setUploading(true);try{const token=await auth.currentUser.getIdToken();const r=await fetch('/api/institution/provision-roster',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({institutionId:institution?.id,institutionName,licenseCount:Number(licenseCount),rows})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Provisioning failed.');setInstitution(d.institution);setMessage(`${rows.length} students provisioned successfully. Unique assessment codes have been generated.`);setRows([]);setFileName('');await load(d.institution.id);}catch(e){setError(e.message||'Unable to provision roster.');}finally{setUploading(false);}};
 const viewReport=async(student)=>{setError('');try{const token=await auth.currentUser.getIdToken();const r=await fetch(`/api/institution/student-report?institutionId=${encodeURIComponent(institution.id)}&rosterId=${encodeURIComponent(student.id)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Report is not ready.');setSelectedReport(d);}catch(e){setError(e.message||'Unable to load report.');}};
 const downloadCodes=()=>{const lines=['Full Name,Class,Section,Roll Number,Unique Access Code,Status'];students.forEach(s=>lines.push([s.fullName,s.className,s.section,s.rollNumber,s.accessCode,s.status].map(v=>`"${String(v||'').replace(/"/g,'""')}"`).join(',')));const blob=new Blob([lines.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${institution?.tenantCode||'institution'}-assessment-codes.csv`;a.click();URL.revokeObjectURL(a.href);};
 const progress=useMemo(()=>({claimed:summary.claimed||0,started:summary.started||0,completed:summary.completed||0,ready:summary.reportsReady||0}),[summary]);
 if(loading)return <div style={{padding:60,textAlign:'center',color:'#64748b',fontWeight:800}}>Loading institutional workspace…</div>;
 if(selectedReport)return <div style={{maxWidth:1100,margin:'0 auto',padding:'25px 18px 60px'}}><button onClick={()=>setSelectedReport(null)} style={{border:'1px solid #cbd5e1',background:'#fff',borderRadius:10,padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>← Back to students</button><div style={{...card,marginTop:14}}><div style={{color:'#4f46e5',fontSize:11,fontWeight:900,letterSpacing:1}}>INSTITUTIONAL REPORT</div><h1 style={{margin:'7px 0'}}>{selectedReport.student.fullName}</h1><p style={{color:'#64748b'}}>{selectedReport.student.className} {selectedReport.student.section}</p><p style={{lineHeight:1.7}}>This report is provided to the institution for educational/career guidance purposes. It should not be used as an automated hiring, promotion or disciplinary decision.</p><pre style={{background:'#f8fafc',padding:15,borderRadius:10,overflow:'auto',fontSize:11}}>{JSON.stringify(selectedReport.report,null,2)}</pre></div></div>;
 return <div style={{minHeight:'100vh',background:'#f8fafc',padding:'24px 18px 60px'}}><div style={{maxWidth:1200,margin:'0 auto'}}><div style={{...card,background:'linear-gradient(135deg,#0f172a,#1e293b)',color:'#fff'}}><div style={{color:'#fbbf24',fontSize:11,fontWeight:900,letterSpacing:1.5}}>VIDYAVANTAGE · INSTITUTIONAL CAREER GUIDANCE</div><h1 style={{margin:'8px 0',fontSize:32}}>Institution Workspace</h1><p style={{margin:0,color:'#cbd5e1'}}>Provision licenses, upload rosters, distribute unique codes and monitor career-assessment progress.</p></div>
 {error&&<div style={{marginTop:14,padding:13,borderRadius:10,background:'#fef2f2',color:'#991b1b',fontWeight:700}}>{error}</div>}{message&&<div style={{marginTop:14,padding:13,borderRadius:10,background:'#ecfdf5',color:'#166534',fontWeight:700}}>{message}</div>}
 {founder&&!institution&&<div style={{...card,marginTop:14}}><h2 style={{marginTop:0}}>Create / provision an institution</h2><p style={{color:'#64748b'}}>This founder workflow creates the tenant record and allocates the purchased assessment licenses.</p><div style={{display:'grid',gridTemplateColumns:'1fr 220px',gap:12}}><input style={input} value={institutionName} onChange={e=>setInstitutionName(e.target.value)} placeholder="Institution name"/><input style={input} type="number" min="3" value={licenseCount} onChange={e=>setLicenseCount(e.target.value)}/></div></div>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginTop:14}}>{[['Purchased',institution?.licenses?.purchased||0],['Available',available],['Started',progress.started],['Completed',progress.completed]].map(([l,v])=><div key={l} style={card}><div style={{fontSize:11,color:'#64748b',fontWeight:900,textTransform:'uppercase'}}>{l}</div><div style={{fontSize:30,fontWeight:950,color:'#0f172a',marginTop:6}}>{v}</div></div>)}</div>
 <div style={{...card,marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>{institution?.name||institutionName||'Institution roster'}</h2><p style={{margin:'4px 0 0',color:'#64748b'}}>Tenant code: {institution?.tenantCode||'Will be generated'}</p></div><div style={{display:'flex',gap:8}}><button onClick={downloadCodes} disabled={!students.length} style={{border:'1px solid #cbd5e1',background:'#fff',borderRadius:10,padding:'10px 13px',fontWeight:800,cursor:'pointer'}}>Export codes CSV</button><label style={{border:0,borderRadius:10,padding:'10px 13px',background:'#4f46e5',color:'#fff',fontWeight:900,cursor:'pointer'}}>Upload roster<input type="file" accept=".csv,.xlsx,.xls,.docx" onChange={e=>e.target.files?.[0]&&parseFile(e.target.files[0])} style={{display:'none'}}/></label></div></div>{fileName&&<div style={{marginTop:12,padding:12,background:'#f8fafc',borderRadius:10,fontSize:13}}><strong>{fileName}</strong> · {rows.length} valid student rows detected</div>}{rows.length>0&&<div style={{marginTop:12}}><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:8,fontSize:11,fontWeight:900,color:'#64748b',padding:'8px 10px'}}>FULL NAME · CLASS · SECTION · ROLL NO.</div>{rows.slice(0,8).map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:8,padding:'9px 10px',borderTop:'1px solid #eef2f7',fontSize:13}}><span>{r.fullName}</span><span>{r.className}</span><span>{r.section}</span><span>{r.rollNumber}</span></div>)}{rows.length>8&&<div style={{padding:10,color:'#64748b',fontSize:12}}>Showing first 8 of {rows.length} rows.</div>}<button onClick={provision} disabled={uploading} style={{marginTop:12,border:0,borderRadius:10,padding:'12px 16px',background:uploading?'#94a3b8':'#0f172a',color:'#fff',fontWeight:900,cursor:'pointer'}}>{uploading?'Provisioning…':`Generate ${rows.length} unique assessment codes`}</button></div>}</div>
 <div style={{...card,marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><h2 style={{margin:0}}>Student licenses</h2><p style={{margin:'4px 0 0',color:'#64748b'}}>Codes are hidden by default. Use the eye control to reveal one code at a time.</p></div><div style={{fontSize:12,color:'#64748b'}}>{progress.claimed} claimed · {progress.completed} completed · {progress.ready} reports ready</div></div><div style={{overflowX:'auto',marginTop:12}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{['Student','Class','Section','Access code','Progress','Report'].map(h=><th key={h} style={{textAlign:'left',padding:'10px',borderBottom:'1px solid #e2e8f0',color:'#64748b',fontSize:11,textTransform:'uppercase'}}>{h}</th>)}</tr></thead><tbody>{students.map(s=><tr key={s.id}><td style={{padding:10,borderBottom:'1px solid #f1f5f9',fontWeight:800}}>{s.fullName}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.className}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.section}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}><span style={{fontFamily:'monospace',letterSpacing:1}}>{revealed[s.id]?s.accessCode:'••••••••••••'}</span><button onClick={()=>setRevealed(x=>({...x,[s.id]:!x[s.id]}))} style={{marginLeft:8,border:0,background:'transparent',cursor:'pointer'}}>{revealed[s.id]?'🙈':'👁️'}</button></td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.assessmentStatus}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}><button onClick={()=>viewReport(s)} disabled={s.reportStatus!=='ready'&&s.assessmentStatus!=='completed'} style={{border:0,borderRadius:8,padding:'7px 10px',background:s.assessmentStatus==='completed'?'#eef2ff':'#f1f5f9',color:s.assessmentStatus==='completed'?'#4338ca':'#94a3b8',fontWeight:800,cursor:'pointer'}}>View report</button></td></tr>)}</tbody></table>{!students.length&&<div style={{padding:35,textAlign:'center',color:'#64748b'}}>Upload a student roster to create institutional licenses.</div>}</div></div>
 </div></div>;
}
