import React from 'react';

const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:22,boxShadow:'0 8px 28px rgba(15,23,42,.05)'};
const NotAvailable=({text='Not assessed / not available in this report.'})=><div style={{padding:14,background:'#f8fafc',border:'1px dashed #cbd5e1',borderRadius:12,color:'#64748b',fontSize:13}}>{text}</div>;
const Section=({title,children})=><section style={{...card,marginTop:14}}><h2 style={{marginTop:0}}>{title}</h2>{children}</section>;
const List=({items=[],render})=>items.length?<div style={{display:'grid',gap:8}}>{items.map((x,i)=><div key={x?.id||x?.name||x?.title||i} style={{padding:12,background:'#f8fafc',borderRadius:10,border:'1px solid #eef2f7'}}>{render?render(x,i):String(x)}</div>)}</div>:<NotAvailable/>;
const MiniBar=({value,label})=><div style={{marginTop:8}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,fontWeight:800,color:'#475569'}}><span>{label}</span><span>{value}%</span></div><div style={{height:8,background:'#eef2f7',borderRadius:99,overflow:'hidden',marginTop:5}}><div style={{height:'100%',width:`${Math.max(0,Math.min(100,value))}%`,background:'#4f46e5',borderRadius:99}}/></div></div>;

export default function InstitutionCareerReportViewV2({selectedReport,onBack}){
 const report=selectedReport?.report||{};const student=selectedReport?.student||{};const scores=report.scores||{};const intake=report.intake||{};const careers=report.careerExploration||[];
 const values=Object.entries(scores.values||{}).sort((a,b)=>Number(b[1])-Number(a[1])).slice(0,8);const big5=Object.entries(scores.big5||{});
 const academics={educationStage:intake.educationStage||report.educationStage||student.educationStage,className:intake.className||student.className,stream:intake.stream||report.stream||student.stream,subjects:intake.subjectsLiked||intake.subjects||report.subjectsLiked||student.subjectsLiked,academicAverage:intake.academicAverage||report.academicAverage||student.academicAverage};
 const environment=report.workEnvironment||report.preferredWorkEnvironment||scores.workEnvironment||report.work_environment;
 const alternatives=report.alternativeCareers||report.alternativeCareerDirections||report.alternatives||careers.slice(3);
 const roadmap=report.actionRoadmap||report.actionPlan||report.nextSteps;const roadmapItems=Array.isArray(roadmap)?roadmap:(roadmap?.items||roadmap?.steps||[]);
 return <div style={{maxWidth:1100,margin:'0 auto',padding:'25px 18px 60px'}}>
  <button onClick={onBack} style={{border:'1px solid #cbd5e1',background:'#fff',borderRadius:10,padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>← Back to students</button>
  <div style={{...card,marginTop:14,background:'linear-gradient(135deg,#0f172a,#1e293b)',color:'#fff'}}><div style={{color:'#fbbf24',fontSize:11,fontWeight:900,letterSpacing:1.5}}>VIDYAVANTAGE · INSTITUTIONAL CAREER REPORT</div><h1 style={{margin:'8px 0 5px',fontSize:32}}>{student.fullName||'Student'}</h1><p style={{margin:0,color:'#cbd5e1'}}>{student.className||'Class not supplied'} {student.section||''} · {student.rollNumber||'Roll no. not supplied'}</p></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginTop:14}}>{[['RIASEC',scores.riasecCode||'—'],['Reasoning',scores.reasoning?.percent!=null?`${scores.reasoning.percent}%`:'—'],['Readiness',scores.readinessPercent!=null?`${scores.readinessPercent}%`:'—'],['Adaptability',scores.adaptabilityPercent!=null?`${scores.adaptabilityPercent}%`:'—']].map(([l,v])=><div key={l} style={card}><div style={{fontSize:11,fontWeight:900,color:'#64748b',textTransform:'uppercase'}}>{l}</div><div style={{fontSize:27,fontWeight:950,marginTop:5,color:'#0f172a'}}>{v}</div></div>)}</div>

  <Section title="1. Assessment coverage"><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10}}>{[['RIASEC',scores.riasecCode],['Big Five',Object.keys(scores.big5||{}).length],['Career values',Object.keys(scores.values||{}).length],['Reasoning',scores.reasoning?.percent]].map(([l,v])=><div key={l} style={{padding:13,background:'#f8fafc',borderRadius:10}}><b>{l}</b><div style={{fontSize:12,color:'#64748b',marginTop:4}}>{v!==undefined&&v!==null&&v!==''?'Available':'Not assessed'}</div></div>)}</div></Section>
  <Section title="2. Academic & developmental context"><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:10}}>{[['Education stage',academics.educationStage],['Class / year',academics.className],['Stream',academics.stream],['Subjects',academics.subjects],['Academic average',academics.academicAverage]].map(([l,v])=><div key={l} style={{padding:13,background:'#f8fafc',borderRadius:10}}><div style={{fontSize:11,fontWeight:900,color:'#64748b',textTransform:'uppercase'}}>{l}</div><div style={{marginTop:5,fontWeight:800}}>{v||'Not supplied'}</div></div>)}</div></Section>
  <Section title="3. Career exploration"><List items={careers.slice(0,8)} render={(c,i)=><><div style={{fontWeight:900}}>{i+1}. {c.name||c.title}</div><div style={{fontSize:12,color:'#64748b',marginTop:3}}>{c.category||c.stream||'Career pathway'} · exploration index {c.explorationIndex??c.matchScore??'—'}</div></>}/></Section>
  <Section title="4. Career values">{values.length?values.map(([k,v])=><MiniBar key={k} label={k} value={Math.round(Number(v)*20)}/>):<NotAvailable text="Career values were not assessed or are not available."/>}</Section>
  <Section title="5. Personality tendencies">{big5.length?<div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:10}}>{big5.map(([k,v])=><div key={k} style={{background:'#f8fafc',borderRadius:12,padding:14,textAlign:'center'}}><div style={{fontWeight:900}}>{k}</div><div style={{fontSize:22,fontWeight:950,marginTop:6}}>{v}</div></div>)}</div>:<NotAvailable text="Big Five data was not assessed in this attempt."/>}</Section>
  <Section title="6. Preferred work environment">{environment?<div style={{padding:16,background:'#f8fafc',borderRadius:12,lineHeight:1.7}}>{typeof environment==='string'?environment:<pre style={{margin:0,whiteSpace:'pre-wrap',fontFamily:'inherit'}}>{JSON.stringify(environment,null,2)}</pre>}</div>:<NotAvailable text="Preferred work environment data is not available in this report."/>}</Section>
  <Section title="7. Alternative & unexpected careers"><List items={alternatives} render={(c,i)=><><div style={{fontWeight:900}}>{i+1}. {c.name||c.title||c}</div>{c.desc&&<div style={{fontSize:12,color:'#64748b',marginTop:4}}>{c.desc}</div>}</>}/></Section>
  <Section title="8. 90-day career action roadmap">{roadmapItems.length?<List items={roadmapItems} render={(x,i)=><><b>{x.title||x.name||`Step ${i+1}`}</b>{x.description&&<div style={{fontSize:13,color:'#64748b',marginTop:4}}>{x.description}</div>}{x.days&&<div style={{fontSize:12,color:'#4f46e5',marginTop:4,fontWeight:800}}>{x.days}</div>}</>}/>:<NotAvailable text="A personalised action roadmap is not yet available in the stored report data."/>}</Section>
  <Section title="Professional-use boundary"><div style={{padding:15,background:'#fffbeb',border:'1px solid #fde68a',borderRadius:12,color:'#713f12',lineHeight:1.7}}>This report is a structured career-exploration aid. It is not a clinical diagnosis, IQ score, hiring decision, disciplinary tool or guarantee of career outcomes. Institutional staff should interpret it alongside student context, academic evidence and qualified career guidance.</div></Section>
 </div>;
}
