import React from 'react';
import InstitutionCareerEvidencePanel from './InstitutionCareerEvidencePanel';
import InstitutionCareerReportCoverage from './InstitutionCareerReportCoverage';
import {buildInstitutionCareerReflection,readInstitutionCareerExploration} from './careerReportDataContract';

const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:20,boxShadow:'0 8px 28px rgba(15,23,42,.05)'};
const muted={color:'#64748b'};
const hasObject=v=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length>0;
const hasArray=v=>Array.isArray(v)&&v.length>0;
const hasValue=v=>v!==undefined&&v!==null&&v!=='';
function SourceBadge({source}){const labels={assessed:'Assessed',derived_from_assessment:'Derived from assessment evidence',career_catalogue:'Career catalogue information',not_assessed:'Not assessed',unavailable:'Not available'};return <span style={{display:'inline-block',fontSize:10,fontWeight:900,color:'#475569',background:'#f1f5f9',borderRadius:999,padding:'4px 8px',marginLeft:8}}>{labels[source]||'Not available'}</span>}
function Block({title,value,children,empty='Not available.'}){return <section style={card}><h3 style={{marginTop:0}}>{title}</h3>{children||(hasObject(value)||hasArray(value)||hasValue(value)?<pre style={{whiteSpace:'pre-wrap',fontSize:12,color:'#475569',margin:0}}>{typeof value==='string'||typeof value==='number'?String(value):JSON.stringify(value,null,2)}</pre>:<p style={{margin:0,...muted}}>{empty}</p>)}</section>}
function EvidenceBlock({title,value,source='assessed'}){return <Block title={<>{title}<SourceBadge source={source}/></>} value={value}/>}
function List({title,value,empty='Not available.'}){const items=Array.isArray(value)?value:[];return <section style={card}><h3 style={{marginTop:0}}>{title}</h3>{items.length?items.slice(0,12).map((x,i)=>{const profile=x.decisionProfile||{};const pathway=profile.pathway||{};const explanation=x.explanation||{};return <div key={x.id||i} style={{padding:'12px 0',borderBottom:'1px solid #eef2f7'}}><div><strong>{x.name||x.title||x.action||`Item ${i+1}`}</strong>{x.category&&<span style={{fontSize:12,...muted}}> · {x.category}</span>}{x.stream&&<span style={{fontSize:12,...muted}}> · {x.stream}</span>}</div>{(x.explorationIndex!=null||x.matchScore!=null||x.interestAlignmentIndex!=null)&&<div style={{fontSize:12,color:'#475569',marginTop:4}}>{x.explorationIndex!=null&&<span>Exploration index: <strong>{x.explorationIndex}</strong> </span>}{x.matchScore!=null&&<span>· Match: <strong>{x.matchScore}</strong> </span>}{x.interestAlignmentIndex!=null&&<span>· Interest alignment: <strong>{x.interestAlignmentIndex}</strong></span>}</div>}{x.rationale&&<div style={{fontSize:12,color:'#475569',marginTop:5,lineHeight:1.5}}><strong>Why this direction:</strong> {String(x.rationale)}</div>}{explanation.whyExplore&&<div style={{fontSize:12,color:'#475569',marginTop:5,lineHeight:1.5}}><strong>Why explore:</strong> {String(explanation.whyExplore)}</div>}{pathway.statusLabel&&<div style={{fontSize:12,color:'#475569',marginTop:5}}><strong>Pathway:</strong> {String(pathway.statusLabel)}</div>}{pathway.listedStreams?.length>0&&<div style={{fontSize:11,...muted,marginTop:3}}>Listed streams: {pathway.listedStreams.join(' · ')}</div>}{explanation.whatToCheck?.length>0&&<div style={{fontSize:11,...muted,marginTop:4}}>Checks: {explanation.whatToCheck.slice(0,3).join(' ')}</div>}</div>}):<p style={{margin:0,...muted}}>{empty}</p>}</section>}
function ScoreCard({label,value,detail}){return <div style={card}><div style={{fontSize:11,fontWeight:900,...muted,textTransform:'uppercase'}}>{label}</div><div style={{fontSize:27,fontWeight:950,marginTop:5}}>{value}</div>{detail&&<div style={{fontSize:12,marginTop:4,...muted}}>{detail}</div>}</div>}

export default function InstitutionCareerReportShell({payload,onBack}){
 const report=payload?.report||{},student=payload?.student||{},intake=report.intake||{},scores=report.scores||{},careers=Array.isArray(report.careerExploration)?report.careerExploration:[],evidence=payload?.assessmentEvidence?.sections||[];
 const contract=buildInstitutionCareerReflection(report); const sectionSource=id=>contract.find(x=>x.id===id)?.source||'unavailable';
 const assessed=id=>Boolean(evidence.find(x=>x.id===id)?.assessed);
 const careerDirectionsSource=careers.length&&assessed('career_directions')?'derived_from_assessment':'unavailable';
 const hasRiasec=assessed('riasec_profile')&&Boolean(scores.riasec||scores.riasecCode),hasReasoning=assessed('reasoning_profile')&&Boolean(scores.reasoning),hasValues=assessed('career_values')&&hasObject(scores.values),hasBig5=assessed('personality_profile')&&hasObject(scores.big5);
 const hasReadiness=assessed('decision_readiness')&&(scores.readinessPercent!=null||hasObject(scores.readiness)),hasAdaptability=assessed('adaptability')&&(scores.adaptabilityPercent!=null||hasObject(scores.adaptability));
 const environmentValue=hasObject(scores.environment)?scores.environment:(hasObject(scores.workEnvironment)?scores.workEnvironment:(hasObject(report.workEnvironment)?report.workEnvironment:null));
 const hasEnvironment=assessed('work_environment')&&hasObject(environmentValue),hasCareerDirections=careerDirectionsSource!=='unavailable';
 const hasTopDirections=sectionSource('top_career_directions')!=='unavailable'&&hasArray(report.topCareerDirections),hasAlternativeCareers=sectionSource('alternative_careers')!=='unavailable'&&hasArray(report.alternativeCareers);
 const hasPathway=sectionSource('pathway_analysis')!=='unavailable'&&(hasObject(report.pathwayAnalysis)||hasArray(report.pathways)),hasStream=sectionSource('stream_analysis')!=='unavailable'&&(hasObject(report.streamAnalysis)||hasArray(report.streamScenarios));
 const hasEducation=sectionSource('education_roadmap')!=='unavailable'&&(hasObject(report.educationRoadmap)||hasObject(report.education)),hasSkills=sectionSource('skills_evidence')!=='unavailable'&&(hasObject(report.skillsEvidence)||hasObject(report.skillsPlan));
 const hasAffordability=sectionSource('affordability')!=='unavailable'&&(hasObject(report.affordability)||hasObject(report.friction)),hasActionRoadmap=sectionSource('action_roadmap')!=='unavailable'&&(hasObject(report.actionRoadmap)||hasObject(report.actionPlan)||hasValue(report.reflection?.recommendedNextStep));
 const hasCounsellorReview=sectionSource('counsellor_review')!=='unavailable'&&(hasObject(report.counsellorReview)||hasObject(report.reviewLimitations));
 const executiveSnapshot=report.executiveSnapshot||report.executiveSummary||report.snapshot;
 const preferenceItems=[['Subjects enjoyed / strongest in',intake.likedSubjects],['Subjects disliked / difficult',intake.dislikedSubjects],['Hobbies / interests',intake.hobbies],['Current curiosity',intake.curiosity],['Stated goal',intake.goal]].filter(([,value])=>Array.isArray(value)?value.length>0:hasValue(value));
 const hasInterestPersonality=hasRiasec||hasBig5;
 const hasStrengthsValuesPreferences=preferenceItems.length>0||hasValues;
 return <div style={{maxWidth:1100,margin:'0 auto',padding:'24px 18px 60px'}}>
  <button type="button" onClick={onBack} style={{border:'1px solid #cbd5e1',background:'#fff',borderRadius:10,padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>← Back to students</button>
  <section style={{...card,marginTop:14,background:'linear-gradient(135deg,#0f172a,#1e293b)',color:'#fff'}}><div style={{color:'#fbbf24',fontSize:11,fontWeight:900,letterSpacing:1.5}}>VIDYAVANTAGE · INSTITUTIONAL CAREER REPORT</div><h1 style={{margin:'8px 0 5px'}}>{student.fullName||'Student Career Report'}</h1><p style={{margin:0,color:'#cbd5e1'}}>{student.className||'Class not supplied'} {student.section||''} · {student.rollNumber||'Roll no. not supplied'}</p></section>
  <InstitutionCareerEvidencePanel assessmentEvidence={payload?.assessmentEvidence}/><InstitutionCareerReportCoverage report={report}/>
  <section style={{...card,marginTop:12}}><h2 style={{marginTop:0}}>Executive snapshot <SourceBadge source={sectionSource('executive_snapshot')}/></h2>{hasValue(executiveSnapshot)?<Block title="Student report snapshot" value={executiveSnapshot}/>:<p style={{margin:'0 0 10px',lineHeight:1.7,...muted}}>{report.reflection?.statement||'This institutional view reflects the persisted Student Career Assessment V2 report. It does not add conclusions that are absent from the student evidence.'}</p>}<div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}>{[['Assessment bundle',report.bundleTitle],['Report tier',report.reportTier],['Completed',report.completedAt?new Date(report.completedAt).toLocaleString():null]].map(([l,v])=><div key={l} style={{background:'#f8fafc',padding:12,borderRadius:10}}><div style={{fontSize:11,...muted}}>{l}</div><div style={{fontWeight:900,marginTop:4}}>{hasValue(v)?String(v):'Not available'}</div></div>)}</div></section>
  <section style={{...card,marginTop:12}}><h3 style={{marginTop:0}}>Academic & developmental context</h3><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10}}>{[['Age',intake.age],['Age band',intake.ageBand],['Education stage',intake.educationStage],['Class / year',intake.className||student.className],['Board / curriculum',intake.board],['Stream',intake.stream],['Academic average',intake.academicAverage],['School / college',intake.institutionName]].map(([l,v])=><div key={l} style={{background:'#f8fafc',padding:12,borderRadius:10}}><div style={{fontSize:11,...muted}}>{l}</div><div style={{fontWeight:900,marginTop:4}}>{hasValue(v)?String(v):'Not supplied'}</div></div>)}</div>{intake.likedSubjects?.length>0&&<div style={{marginTop:10,fontSize:13}}><strong>Subjects enjoyed / strongest in:</strong> {intake.likedSubjects.join(', ')}</div>}{intake.dislikedSubjects?.length>0&&<div style={{marginTop:8,fontSize:13}}><strong>Subjects disliked / difficult:</strong> {intake.dislikedSubjects.join(', ')}</div>}{hasValue(intake.hobbies)&&<div style={{marginTop:8,fontSize:13}}><strong>Hobbies / interests:</strong> {intake.hobbies}</div>}{hasValue(intake.curiosity)&&<div style={{marginTop:8,fontSize:13}}><strong>Current curiosity:</strong> {intake.curiosity}</div>}{hasValue(intake.goal)&&<div style={{marginTop:8,fontSize:13}}><strong>Stated goal:</strong> {intake.goal}</div>}</section>
  <section style={{...card,marginTop:12}}><h3 style={{marginTop:0}}>Interests & personality tendencies <SourceBadge source={sectionSource('interest_personality')}/></h3>{hasInterestPersonality?<div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:12}}>{hasRiasec?<div style={{background:'#f8fafc',padding:14,borderRadius:12}}><div style={{fontSize:11,fontWeight:900,...muted}}>RIASEC interest evidence</div><div style={{fontSize:26,fontWeight:950,marginTop:5}}>{scores.riasecCode||'Profile available'}</div></div>:<div style={{background:'#f8fafc',padding:14,borderRadius:12,...muted}}>RIASEC not assessed.</div>}{hasBig5?<div style={{background:'#f8fafc',padding:14,borderRadius:12}}><div style={{fontSize:11,fontWeight:900,...muted}}>Big Five personality evidence</div><div style={{marginTop:5,fontWeight:800}}>Assessed</div></div>:<div style={{background:'#f8fafc',padding:14,borderRadius:12,...muted}}>Personality not assessed.</div>}</div>:<p style={{margin:0,...muted}}>Not assessed.</p>}</section>
  <section style={{...card,marginTop:12}}><h3 style={{marginTop:0}}>Strengths, values & preferences <SourceBadge source={sectionSource('strengths_values')}/></h3>{hasStrengthsValuesPreferences?<div>{preferenceItems.map(([label,value])=><div key={label} style={{marginTop:8,fontSize:13}}><strong>{label}:</strong> {Array.isArray(value)?value.join(', '):String(value)}</div>)}{hasValues&&<div style={{marginTop:12}}><strong>Career values evidence:</strong><pre style={{whiteSpace:'pre-wrap',fontSize:12,color:'#475569',margin:'6px 0 0'}}>{JSON.stringify(scores.values,null,2)}</pre></div>}</div>:<p style={{margin:0,...muted}}>Not available in this assessment.</p>}</section>
  <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginTop:12}}>{hasRiasec?<ScoreCard label="RIASEC" value={scores.riasecCode||'Profile available'} detail="Career interest evidence"/>:<ScoreCard label="RIASEC" value="Not assessed"/>}{hasReasoning?<ScoreCard label="Reasoning sampler" value={scores.reasoning?.percent!=null?`${scores.reasoning.percent}%`:'Profile available'} detail="Observed sampler performance"/>:<ScoreCard label="Reasoning sampler" value="Not assessed"/>}{hasValues?<ScoreCard label="Career values" value="Assessed" detail="Values evidence available"/>:<ScoreCard label="Career values" value="Not assessed"/>}{hasBig5?<ScoreCard label="Personality" value="Assessed" detail="Big Five evidence available"/>:<ScoreCard label="Personality" value="Not assessed"/>}</div>
  {hasRiasec?<Block title={<>Career interest profile<SourceBadge source={sectionSource('riasec_profile')}/></>}><div style={{fontSize:36,fontWeight:950,letterSpacing:6,color:'#4f46e5'}}>{scores.riasecCode||'—'}</div><div style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:8,marginTop:12}}>{Object.entries(scores.riasec||{}).map(([k,v])=><div key={k} style={{background:'#f8fafc',borderRadius:10,padding:10,textAlign:'center'}}><strong>{k}</strong><div style={{marginTop:4}}>{v}</div></div>)}</div></Block>:<EvidenceBlock title="Career interest profile" source={sectionSource('riasec_profile')}/>} 
  {hasBig5?<Block title={<>Personality tendencies<SourceBadge source={sectionSource('personality_profile')}/></>} value={scores.big5}/>:<EvidenceBlock title="Personality tendencies" source={sectionSource('personality_profile')}/>} {hasValues?<Block title={<>Career values<SourceBadge source={sectionSource('career_values')}/></>} value={scores.values}/>:<EvidenceBlock title="Career values" source={sectionSource('career_values')}/>} {hasReasoning?<Block title={<>Reasoning sampler<SourceBadge source={sectionSource('reasoning_profile')}/></>}><p style={{margin:0,...muted}}>Observed correct-response rate in the reasoning sampler: <strong>{scores.reasoning?.percent!=null?`${scores.reasoning.percent}%`:'Not available'}</strong>. This is not an IQ score or norm-referenced percentile.</p></Block>:<EvidenceBlock title="Reasoning sampler" source={sectionSource('reasoning_profile')}/>} 
  {hasCareerDirections?<List title={<>Career directions to explore<SourceBadge source={careerDirectionsSource}/></>} value={readInstitutionCareerExploration(report)||careers}/>:<EvidenceBlock title="Career directions to explore" source={careerDirectionsSource}/>} {hasTopDirections?<List title={<>Top career directions<SourceBadge source={sectionSource('top_career_directions')}/></>} value={report.topCareerDirections}/>:<EvidenceBlock title="Top career directions" source={sectionSource('top_career_directions')}/>} 
  {hasReadiness?<EvidenceBlock title="Career decision readiness" value={scores.readinessPercent!=null?{percent:scores.readinessPercent,...scores.readiness}:scores.readiness} source={sectionSource('decision_readiness')}/>:<EvidenceBlock title="Career decision readiness" source={sectionSource('decision_readiness')}/>} 
  {hasAdaptability?<EvidenceBlock title="Adaptability & career resilience" value={scores.adaptabilityPercent!=null?{percent:scores.adaptabilityPercent,...scores.adaptability}:scores.adaptability} source={sectionSource('adaptability')}/>:<EvidenceBlock title="Adaptability & career resilience" source={sectionSource('adaptability')}/>} 
  {hasEnvironment?<EvidenceBlock title="Preferred work environment" value={environmentValue} source={sectionSource('work_environment')}/>:<EvidenceBlock title="Preferred work environment" source={sectionSource('work_environment')}/>} 
  {hasPathway?<EvidenceBlock title="Non-linear pathway analysis" value={report.pathwayAnalysis||report.pathways} source={sectionSource('pathway_analysis')}/>:<EvidenceBlock title="Non-linear pathway analysis" source={sectionSource('pathway_analysis')}/>} 
  {hasStream?<EvidenceBlock title="Stream & subject scenarios" value={report.streamAnalysis||report.streamScenarios} source={sectionSource('stream_analysis')}/>:<EvidenceBlock title="Stream & subject scenarios" source={sectionSource('stream_analysis')}/>} 
  {hasEducation?<EvidenceBlock title="Education roadmap" value={report.educationRoadmap||report.education} source={sectionSource('education_roadmap')}/>:<EvidenceBlock title="Education roadmap" source={sectionSource('education_roadmap')}/>} 
  {hasSkills?<EvidenceBlock title="Skills & evidence plan" value={report.skillsEvidence||report.skillsPlan} source={sectionSource('skills_evidence')}/>:<EvidenceBlock title="Skills & evidence plan" source={sectionSource('skills_evidence')}/>} 
  {hasAffordability?<EvidenceBlock title="Affordability, scholarships & friction" value={report.affordability||report.friction} source={sectionSource('affordability')}/>:<EvidenceBlock title="Affordability, scholarships & friction" source={sectionSource('affordability')}/>} 
  {hasAlternativeCareers?<List title={<>Alternative & unexpected careers<SourceBadge source={sectionSource('alternative_careers')}/></>} value={report.alternativeCareers}/>:<EvidenceBlock title="Alternative & unexpected careers" source={sectionSource('alternative_careers')}/>} 
  {hasActionRoadmap?<EvidenceBlock title="90-day career action roadmap" value={report.actionRoadmap||report.actionPlan||{recommendedNextStep:report.reflection?.recommendedNextStep}} source={sectionSource('action_roadmap')}/>:<EvidenceBlock title="90-day career action roadmap" source={sectionSource('action_roadmap')}/>} 
  {hasCounsellorReview?<EvidenceBlock title="Counsellor conversation & limitations" value={report.counsellorReview||report.reviewLimitations} source={sectionSource('counsellor_review')}/>:<EvidenceBlock title="Counsellor conversation & limitations" source={sectionSource('counsellor_review')}/>} 
  <section style={{...card,marginTop:12,background:'#fffbeb',borderColor:'#fde68a'}}><h3 style={{marginTop:0}}>Professional-use boundary</h3><p style={{margin:0,color:'#713f12',lineHeight:1.7}}>This is an institutional career-exploration aid. It is not a clinical diagnosis, IQ score, norm-referenced percentile, hiring decision, disciplinary tool or guarantee of outcomes. Missing assessment evidence must not be interpreted as a negative result.</p></section>
 </div>;
}
