import React,{useEffect,useMemo,useState} from 'react';
import {auth} from '../firebase';
import InstitutionCareerReportShell from './InstitutionCareerReportShell';

const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:22,boxShadow:'0 8px 28px rgba(15,23,42,.05)'};
const input={width:'100%',padding:'12px 13px',border:'1px solid #dbe3ef',borderRadius:10,fontSize:13,outline:'none',boxSizing:'border-box'};
const normaliseHeader=(v)=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function mapRows(raw){if(!Array.isArray(raw)||!raw.length)return[];const headers=(raw[0]||[]).map(normaliseHeader);const find=(names)=>{const i=headers.findIndex(h=>names.includes(h));return i>=0?i:null;};const name=find(['fullname','studentname','name','student']);const cls=find(['class','grade','classname','standard']);const sec=find(['section','division']);const roll=find(['rollnumber','rollno','roll']);return raw.slice(1).map((r)=>({fullName:name!=null?String(r[name]||'').trim():'',className:cls!=null?String(r[cls]||'').trim():'',section:sec!=null?String(r[sec]||'').trim():'',rollNumber:roll!=null?String(r[roll]||'').trim():''})).filter(x=>x.fullName);}
const pct=(n,d)=>d?Math.round((n/d)*100):0;
const statusLabel=(s)=>({not_started:'Not started',in_progress:'In progress',completed:'Completed'}[s]||s||'Not started');
const statusTone=(s)=>s==='completed'?'#15803d':s==='in_progress'?'#b45309':'#64748b';

function MiniBar({value,label}){return <div style={{marginTop:8}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,fontWeight:800,color:'#475569'}}><span>{label}</span><span>{value}%</span></div><div style={{height:8,background:'#eef2f7',borderRadius:99,overflow:'hidden',marginTop:5}}><div style={{height:'100%',width:`${Math.max(0,Math.min(100,value))}%`,background:'#4f46e5',borderRadius:99}}/></div></div>}

export default function InstitutionCareerDashboard(){
 const [institution,setInstitution]=useState(null);const [students,setStudents]=useState([]);const [summary,setSummary]=useState({});const [fileName,setFileName]=useState('');const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [uploading,setUploading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [revealed,setRevealed]=useState({});const [institutionName,setInstitutionName]=useState('');const [licenseCount,setLicenseCount]=useState('150');const [selectedReport,setSelectedReport]=useState(null);const [classFilter,setClassFilter]=useState('All');const [statusFilter,setStatusFilter]=useState('All');const [search,setSearch]=useState('');
 const founder=auth.currentUser?.email?.toLowerCase()==='antonio.antonio.noronha@gmail.com';
 const load=async(id='')=>{try{const token=await auth.currentUser?.getIdToken();if(!token)return;const url=id?`/api/institution/dashboard?institutionId=${encodeURIComponent(id)}`:'/api/institution/dashboard';const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to load institution dashboard.');setInstitution(d.institution);setStudents(d.students||[]);setSummary(d.summary||{});setInstitutionName(d.institution?.name||'');}catch(e){setError(e.message||'Unable to load institution.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const available=Number(institution?.licenses?.available||0);const paid=institution?.paymentStatus==='paid';
 const classes=useMemo(()=>['All',...Array.from(new Set(students.map(s=>s.className).filter(Boolean))).sort()],[students]);
 const filtered=useMemo(()=>students.filter(s=>{const q=search.trim().toLowerCase();return (classFilter==='All'||s.className===classFilter)&&(statusFilter==='All'||s.assessmentStatus===statusFilter)&&(!q||`${s.fullName} ${s.rollNumber} ${s.section}`.toLowerCase().includes(q));}),[students,classFilter,statusFilter,search]);
 const classStats=useMemo(()=>classes.filter(c=>c!=='All').map(c=>{const list=students.filter(s=>s.className===c);return {className:c,total:list.length,completed:list.filter(s=>s.assessmentStatus==='completed').length,started:list.filter(s=>s.assessmentStatus==='in_progress').length};}),[classes,students]);
 const parseFile=async(file)=>{setError('');setMessage('');setFileName(file.name);try{const ext=file.name.toLowerCase().split('.').pop();if(ext==='csv'){const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);setRows(mapRows(lines.map(line=>line.split(',').map(v=>v.trim().replace(/^\"|\"$/g,'')))));return;}if(ext==='xlsx'||ext==='xls'){const XLSX=await import('xlsx');const buffer=await file.arrayBuffer();const wb=XLSX.read(buffer,{type:'array'});const sheet=wb.Sheets[wb.SheetNames[0]];setRows(mapRows(XLSX.utils.sheet_to_json(sheet,{header:1,defval:''})));return;}if(ext==='docx'){const mammoth=await import('mammoth');const buffer=await file.arrayBuffer();const result=await mammoth.extractRawText({arrayBuffer:buffer});const lines=result.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);setRows(mapRows(lines.map(line=>line.includes('\t')?line.split('\t'):line.split(/\s{2,}/))));return;}throw new Error('Supported formats are CSV, Excel (.xlsx/.xls) and Word (.docx).');}catch(e){setRows([]);setError(e.message||'Unable to read this roster file.');}};
 const provision=async()=>{setError('');setMessage('');if(!rows.length){setError('Please upload a roster first.');return;}if(founder&&!institutionName.trim()){setError('Enter the institution name.');return;}if(founder&&Number(licenseCount)<rows.length){setError(`You are uploading ${rows.length} students but only ${licenseCount} licenses were allocated.`);return;}if(!founder&&rows.length>available){setError(`Only ${available} licenses remain.`);return;}setUploading(true);try{const token=await auth.currentUser.getIdToken();const r=await fetch('/api/institution/provision-roster',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({institutionId:institution?.id,institutionName,licenseCount:Number(licenseCount),rows})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Provisioning failed.');setMessage(`${rows.length} students provisioned successfully. Unique assessment codes have been generated.`);setRows([]);setFileName('');await load(d.institution.id);}catch(e){setError(e.message||'Unable to provision roster.');}finally{setUploading(false);}};
 const viewReport=async(student)=>{setError('');try{const token=await auth.currentUser.getIdToken();const r=await fetch(`/api/institution/student-report?institutionId=${encodeURIComponent(institution.id)}&rosterId=${encodeURIComponent(student.id)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Report is not ready.');setSelectedReport(d);}catch(e){setError(e.message||'Unable to load report.');}};
 const downloadCodes=()=>{const lines=['Full Name,Class,Section,Roll Number,Unique Access Code,Status'];students.forEach(s=>lines.push([s.fullName,s.className,s.section,s.rollNumber,s.accessCode,s.status].map(v=>`\"${String(v||'').replace(/\"/g,'\"\"')}\"`).join(',')));const blob=new Blob([lines.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${institution?.tenantCode||'institution'}-assessment-codes.csv`;a.click();URL.revokeObjectURL(a.href);};
 if(loading)return <div style={{padding:60,textAlign:'center',color:'#64748b',fontWeight:800}}>Loading institutional workspace…</div>;
 if(selectedReport)return <InstitutionCareerReportShell payload={selectedReport} onBack={()=>setSelectedReport(null)}/>;
 const total=students.length;const claimed=summary.claimed||0;const started=summary.started||0;const completed=summary.completed||0;const ready=summary.reportsReady||0;const utilisation=institution?.licenses?.purchased?pct(institution.licenses.used||0,institution.licenses.purchased):0;
 return <div style={{minHeight:'100vh',background:'#f8fafc',padding:'24px 18px 60px'}}><style>{`@media(max-width:800px){.ss-grid-4{grid-template-columns:1fr 1fr!important}.ss-grid-2{grid-template-columns:1fr!important}.ss-table{min-width:850px}}`}</style><div style={{maxWidth:1200,margin:'0 auto'}}>
 <div style={{...card,background:'linear-gradient(135deg,#0f172a,#1e293b)',color:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',flexWrap:'wrap'}}><div><div style={{color:'#fbbf24',fontSize:11,fontWeight:900,letterSpacing:1.5}}>VIDYAVANTAGE · INSTITUTIONAL CAREER GUIDANCE</div><h1 style={{margin:'8px 0',fontSize:32}}>Institution Workspace</h1><p style={{margin:0,color:'#cbd5e1'}}>Manage licensed assessments, student access and career-guidance progress.</p></div><div style={{padding:'10px 13px',borderRadius:999,background:paid?'rgba(34,197,94,.16)':'rgba(251,191,36,.15)',color:paid?'#86efac':'#fde68a',fontWeight:900,fontSize:12}}>{paid?'● ENTITLEMENT ACTIVE':'● PAYMENT / ENTITLEMENT PENDING'}</div></div></div>
 {error&&<div style={{marginTop:14,padding:13,borderRadius:10,background:'#fef2f2',color:'#991b1b',fontWeight:700}}>{error}</div>}{message&&<div style={{marginTop:14,padding:13,borderRadius:10,background:'#ecfdf5',color:'#166534',fontWeight:700}}>{message}</div>}
 {!paid&&!founder&&<div style={{...card,marginTop:14,background:'#fffbeb',borderColor:'#fde68a'}}><strong style={{color:'#92400e'}}>Institution activation is pending.</strong><p style={{margin:'6px 0 0',color:'#78350f',lineHeight:1.6}}>Your workspace is visible, but student access codes and institutional reports remain locked until the institutional entitlement is activated.</p></div>}
 {founder&&!institution&&<div style={{...card,marginTop:14}}><h2 style={{marginTop:0}}>Create / provision an institution</h2><p style={{color:'#64748b'}}>Founder provisioning creates the tenant record and allocates the assessment license pool. Payment can subsequently be marked active from the Super Admin workflow.</p><div className="ss-grid-2" style={{display:'grid',gridTemplateColumns:'1fr 220px',gap:12}}><input style={input} value={institutionName} onChange={e=>setInstitutionName(e.target.value)} placeholder="Institution name"/><input style={input} type="number" min="1" value={licenseCount} onChange={e=>setLicenseCount(e.target.value)}/></div></div>}
 <div className="ss-grid-4" style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginTop:14}}>{[['Students',total],['Claimed',claimed],['In progress',Math.max(0,started-completed)],['Completed',completed]].map(([l,v])=><div key={l} style={card}><div style={{fontSize:11,color:'#64748b',fontWeight:900,textTransform:'uppercase'}}>{l}</div><div style={{fontSize:30,fontWeight:950,color:'#0f172a',marginTop:6}}>{v}</div></div>)}</div>
 <div className="ss-grid-2" style={{display:'grid',gridTemplateColumns:'1.2fr .8fr',gap:14,marginTop:14}}><div style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h2 style={{margin:'0 0 4px'}}>Assessment funnel</h2><p style={{margin:0,color:'#64748b',fontSize:13}}>Track where students are in the journey.</p></div><div style={{fontWeight:950,color:'#4f46e5',fontSize:20}}>{pct(completed,total)}%</div></div><MiniBar label="Claimed access" value={pct(claimed,total)}/><MiniBar label="Started" value={pct(started,total)}/><MiniBar label="Completed" value={pct(completed,total)}/><MiniBar label="Reports ready" value={pct(ready,total)}/></div><div style={card}><h2 style={{margin:'0 0 4px'}}>License utilisation</h2><p style={{margin:0,color:'#64748b',fontSize:13}}>{institution?.licenses?.used||0} of {institution?.licenses?.purchased||0} licenses allocated.</p><div style={{height:16,background:'#eef2f7',borderRadius:99,overflow:'hidden',marginTop:20}}><div style={{height:'100%',width:`${utilisation}%`,background:'#0f172a',borderRadius:99}}/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:8,fontSize:12,fontWeight:800}}><span>{utilisation}% used</span><span>{available} available</span></div></div></div>
 <div style={{...card,marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>{institution?.name||institutionName||'Institution roster'}</h2><p style={{margin:'4px 0 0',color:'#64748b'}}>Tenant: {institution?.tenantCode||'Will be generated'} · Payment: {institution?.paymentStatus||'pending'}</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={downloadCodes} disabled={!students.length||(!paid&&!founder)} style={{border:'1px solid #cbd5e1',background:'#fff',borderRadius:10,padding:'10px 13px',fontWeight:800,cursor:'pointer'}}>Export codes CSV</button><label style={{border:0,borderRadius:10,padding:'10px 13px',background:paid||founder?'#4f46e5':'#94a3b8',color:'#fff',fontWeight:900,cursor:paid||founder?'pointer':'not-allowed'}}>Upload roster<input type="file" accept=".csv,.xlsx,.xls,.docx" disabled={!paid&&!founder} onChange={e=>e.target.files?.[0]&&parseFile(e.target.files[0])} style={{display:'none'}}/></label></div></div>{fileName&&<div style={{marginTop:12,padding:12,background:'#f8fafc',borderRadius:10,fontSize:13}}><strong>{fileName}</strong> · {rows.length} valid student rows detected</div>}{rows.length>0&&<div style={{marginTop:12}}><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:8,fontSize:11,fontWeight:900,color:'#64748b',padding:'8px 10px'}}>FULL NAME · CLASS · SECTION · ROLL NO.</div>{rows.slice(0,8).map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:8,padding:'9px 10px',borderTop:'1px solid #eef2f7',fontSize:13}}><span>{r.fullName}</span><span>{r.className}</span><span>{r.section}</span><span>{r.rollNumber}</span></div>)}{rows.length>8&&<div style={{padding:10,color:'#64748b',fontSize:12}}>Showing first 8 of {rows.length} rows.</div>}<button onClick={provision} disabled={uploading} style={{marginTop:12,border:0,borderRadius:10,padding:'12px 16px',background:uploading?'#94a3b8':'#0f172a',color:'#fff',fontWeight:900,cursor:'pointer'}}>{uploading?'Provisioning…':`Generate ${rows.length} unique assessment codes`}</button></div>}</div>
 <div style={{...card,marginTop:14}}><h2 style={{marginTop:0}}>Class / section snapshot</h2>{classStats.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{['Class','Students','Started','Completed','Completion'].map(h=><th key={h} style={{textAlign:'left',padding:'10px',borderBottom:'1px solid #e2e8f0',color:'#64748b',fontSize:11,textTransform:'uppercase'}}>{h}</th>)}</tr></thead><tbody>{classStats.map(s=><tr key={s.className}><td style={{padding:10,borderBottom:'1px solid #f1f5f9',fontWeight:900}}>{s.className}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.total}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.started}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.completed}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9',fontWeight:900}}>{pct(s.completed,s.total)}%</td></tr>)}</tbody></table></div>:<p style={{color:'#64748b'}}>Class analytics will appear after students are provisioned.</p>}</div>
 <div style={{...card,marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Student management</h2><p style={{margin:'4px 0 0',color:'#64748b'}}>Access codes are masked. Reports are available only after assessment completion.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input style={{...input,width:220}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student / roll no."/><select style={{...input,width:140}} value={classFilter} onChange={e=>setClassFilter(e.target.value)}>{classes.map(c=><option key={c}>{c}</option>)}</select><select style={{...input,width:140}} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="All">All status</option><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></div></div><div style={{overflowX:'auto',marginTop:12}}><table className="ss-table" style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{['Student','Class','Section','Access code','Progress','Report'].map(h=><th key={h} style={{textAlign:'left',padding:'10px',borderBottom:'1px solid #e2e8f0',color:'#64748b',fontSize:11,textTransform:'uppercase'}}>{h}</th>)}</tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td style={{padding:10,borderBottom:'1px solid #f1f5f9',fontWeight:800}}>{s.fullName}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.className||'—'}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.section||'—'}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}>{s.accessCodeAvailable&&s.accessCode?<><span style={{fontFamily:'monospace',letterSpacing:1}}>{revealed[s.id]?s.accessCode:'••••••••••••'}</span><button onClick={()=>setRevealed(x=>({...x,[s.id]:!x[s.id]}))} style={{marginLeft:8,border:0,background:'transparent',cursor:'pointer'}}>{revealed[s.id]?'🙈':'👁️'}</button></>:<span style={{fontSize:12,color:'#94a3b8'}}>Locked</span>}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9',fontWeight:800,color:statusTone(s.assessmentStatus)}}>{statusLabel(s.assessmentStatus)}</td><td style={{padding:10,borderBottom:'1px solid #f1f5f9'}}><button onClick={()=>viewReport(s)} disabled={s.assessmentStatus!=='completed'} style={{border:0,borderRadius:8,padding:'7px 10px',background:s.assessmentStatus==='completed'?'#eef2ff':'#f1f5f9',color:s.assessmentStatus==='completed'?'#4338ca':'#94a3b8',fontWeight:800,cursor:s.assessmentStatus==='completed'?'pointer':'not-allowed'}}>View report</button></td></tr>)}</tbody></table>{!filtered.length&&<div style={{padding:35,textAlign:'center',color:'#64748b'}}>No students match the current filters.</div>}</div></div>
 </div></div>;
}
