// ─────────────────────────────────────────────────────────────────────────────
// INLINE STYLES — shared across ProfileEditor sub-components
// ─────────────────────────────────────────────────────────────────────────────

export const S = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(13,17,23,0.72)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    zIndex: 2000,
    padding: '24px 16px',
    overflowY: 'auto',
  },
  modal: {
    background: '#FFFFFF',
    borderRadius: '24px',
    width: '100%',
    maxWidth: '720px',
    boxShadow: '0 24px 80px rgba(0,0,0,0.22)',
    display: 'flex',
    flexDirection: 'column',
    marginBottom: '24px',
  },
  header: {
    padding: '28px 32px 20px',
    borderBottom: '1px solid #E1E7EF',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    position: 'sticky',
    top: 0,
    background: 'white',
    borderRadius: '24px 24px 0 0',
    zIndex: 10,
  },
  headerLeft: { flex: 1 },
  headerTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: '22px',
    fontWeight: '700',
    color: '#0D1117',
    marginBottom: '4px',
  },
  headerSub: { fontSize: '13px', color: '#6B7280', fontWeight: '500' },
  closeBtn: {
    background: '#F6F8FA',
    border: '1.5px solid #E1E7EF',
    borderRadius: '50%',
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: '18px',
    color: '#6B7280',
    flexShrink: 0,
    lineHeight: 1,
  },
  xpBanner: {
    margin: '20px 32px 0',
    background: 'linear-gradient(135deg, #FFFBEB, #FEF3C7)',
    border: '1.5px solid #FDE68A',
    borderRadius: '14px',
    padding: '14px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  xpBannerLeft: { display: 'flex', alignItems: 'center', gap: '10px' },
  xpBannerIcon: { fontSize: '24px' },
  xpBannerLabel: { fontSize: '12px', fontWeight: '700', color: '#92400E', textTransform: 'uppercase', letterSpacing: '0.5px' },
  xpBannerValue: { fontFamily: "'Fraunces', serif", fontSize: '28px', fontWeight: '900', color: '#D97706', lineHeight: 1 },
  xpBannerSub: { fontSize: '11px', color: '#B45309', fontWeight: '500', marginTop: '2px' },
  body: { padding: '24px 32px 120px', display: 'flex', flexDirection: 'column', gap: '28px' },
  section: {
    background: '#F6F8FA',
    borderRadius: '16px',
    border: '1.5px solid #E1E7EF',
    overflow: 'hidden',
  },
  sectionHeader: {
    padding: '16px 20px',
    background: 'white',
    borderBottom: '1px solid #E1E7EF',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  sectionIcon: { fontSize: '20px' },
  sectionTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: '16px',
    fontWeight: '700',
    color: '#0D1117',
  },
  sectionBody: { padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px' },
  // Sub-section card for each education tier
  tierCard: {
    background: 'white',
    borderRadius: '12px',
    border: '1.5px solid #E1E7EF',
    overflow: 'hidden',
    marginTop: '8px',
  },
  tierCardHeader: {
    padding: '12px 16px',
    background: 'linear-gradient(135deg, #EEF2FF, #E0E7FF)',
    borderBottom: '1px solid #C7D2FE',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  tierCardTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: '14px',
    fontWeight: '700',
    color: '#3730A3',
  },
  tierCardBody: { padding: '16px', display: 'flex', flexDirection: 'column', gap: '14px' },
  fieldGroup: { display: 'flex', flexDirection: 'column', gap: '6px' },
  label: { fontSize: '12px', fontWeight: '700', color: '#374151', textTransform: 'uppercase', letterSpacing: '0.5px' },
  input: {
    width: '100%',
    padding: '10px 14px',
    border: '1.5px solid #E1E7EF',
    borderRadius: '10px',
    fontSize: '14px',
    fontFamily: 'inherit',
    color: '#0D1117',
    background: 'white',
    outline: 'none',
    transition: 'border-color 0.2s',
    boxSizing: 'border-box',
  },
  inputDisabled: {
    background: '#F6F8FA',
    color: '#9CA3AF',
    cursor: 'not-allowed',
  },
  select: {
    width: '100%',
    padding: '10px 14px',
    border: '1.5px solid #E1E7EF',
    borderRadius: '10px',
    fontSize: '14px',
    fontFamily: 'inherit',
    color: '#0D1117',
    background: 'white',
    outline: 'none',
    cursor: 'pointer',
  },
  twoCol: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' },
  tagRow: { display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '4px' },
  tag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: '#EEF2FF',
    border: '1px solid #C7D2FE',
    color: '#4338CA',
    fontSize: '12px',
    fontWeight: '600',
    padding: '4px 10px',
    borderRadius: '20px',
  },
  tagRemove: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#6366F1',
    fontSize: '14px',
    lineHeight: 1,
    padding: '0',
    display: 'flex',
    alignItems: 'center',
  },
  tagInputRow: { display: 'flex', gap: '8px' },
  tagAddBtn: {
    padding: '10px 16px',
    background: '#4F46E5',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    fontFamily: 'inherit',
  },
  toggleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    background: 'white',
    borderRadius: '10px',
    border: '1.5px solid #E1E7EF',
  },
  toggleLabel: { fontSize: '13px', fontWeight: '600', color: '#374151' },
  toggleTrack: (on) => ({
    width: '44px',
    height: '24px',
    borderRadius: '12px',
    background: on ? '#4F46E5' : '#D1D5DB',
    position: 'relative',
    cursor: 'pointer',
    transition: 'background 0.2s',
    flexShrink: 0,
  }),
  toggleThumb: (on) => ({
    position: 'absolute',
    top: '3px',
    left: on ? '23px' : '3px',
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    background: 'white',
    boxShadow: '0 1px 4px rgba(0,0,0,0.2)',
    transition: 'left 0.2s',
  }),
  marksTypeRow: { display: 'flex', gap: '8px' },
  marksTypeBtn: (active) => ({
    flex: 1,
    padding: '9px 12px',
    border: active ? '2px solid #4F46E5' : '1.5px solid #E1E7EF',
    borderRadius: '10px',
    background: active ? '#EEF2FF' : 'white',
    color: active ? '#4338CA' : '#6B7280',
    fontSize: '12px',
    fontWeight: '700',
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.15s',
  }),
  cgpaHint: {
    background: '#F0FDF4',
    border: '1px solid #A7F3D0',
    borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#065F46',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  picPreview: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '2px solid #E1E7EF',
    flexShrink: 0,
  },
  picPlaceholder: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #E8650A, #F0A500)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    color: 'white',
    flexShrink: 0,
  },
  picRow: { display: 'flex', alignItems: 'center', gap: '16px' },
  uploadBtn: {
    padding: '9px 16px',
    background: 'white',
    border: '1.5px solid #E1E7EF',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#374151',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  footer: {
    padding: '20px 32px',
    borderTop: '1px solid #E1E7EF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    background: 'white',
    borderRadius: '0 0 24px 24px',
    position: 'sticky',
    bottom: 0,
  },
  footerLeft: { fontSize: '12px', color: '#6B7280', fontWeight: '500' },
  footerRight: { display: 'flex', gap: '10px' },
  cancelBtn: {
    padding: '10px 20px',
    background: 'white',
    border: '1.5px solid #E1E7EF',
    borderRadius: '50px',
    fontSize: '13px',
    fontWeight: '700',
    color: '#6B7280',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  saveBtn: {
    padding: '10px 24px',
    background: 'linear-gradient(135deg, #E8650A, #F0A500)',
    border: 'none',
    borderRadius: '50px',
    fontSize: '13px',
    fontWeight: '700',
    color: 'white',
    cursor: 'pointer',
    fontFamily: 'inherit',
    boxShadow: '0 4px 14px rgba(232,101,10,0.3)',
  },
  saveBtnDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  // ── Disclaimer box styles ──────────────────────────────────────────────────
  disclaimerBox: {
    background: 'linear-gradient(135deg, #FFF1F2, #FEE2E2)',
    border: '2.5px solid #F87171',
    borderRadius: '16px',
    padding: '20px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  disclaimerHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  disclaimerIcon: { fontSize: '24px', flexShrink: 0 },
  disclaimerTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: '16px',
    fontWeight: '900',
    color: '#991B1B',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  disclaimerBody: {
    fontSize: '13px',
    color: '#7F1D1D',
    lineHeight: '1.7',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  disclaimerPoint: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-start',
  },
  disclaimerBullet: { flexShrink: 0, marginTop: '2px' },
  disclaimerEmergency: {
    background: '#FEF2F2',
    border: '1.5px solid #FECACA',
    borderRadius: '10px',
    padding: '12px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  disclaimerEmergencyTitle: {
    fontSize: '12px',
    fontWeight: '800',
    color: '#991B1B',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  disclaimerEmergencyItem: {
    fontSize: '13px',
    color: '#7F1D1D',
    fontWeight: '600',
  },
  consentRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    background: 'white',
    border: '2px solid #F87171',
    borderRadius: '10px',
    padding: '12px 16px',
    cursor: 'pointer',
  },
  consentCheckbox: {
    width: '18px',
    height: '18px',
    flexShrink: 0,
    marginTop: '2px',
    accentColor: '#DC2626',
    cursor: 'pointer',
  },
  consentLabel: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#991B1B',
    lineHeight: '1.5',
    cursor: 'pointer',
  },
  infoNote: {
    fontSize: '11px',
    color: '#9CA3AF',
    fontWeight: '500',
    marginTop: '4px',
  },
  disabledNote: {
    fontSize: '11px',
    color: '#F59E0B',
    fontWeight: '600',
    marginTop: '4px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
};
