import React, { useEffect, useState } from 'react';
import { auth } from '../../firebase';

const PRODUCT = 'student_games_pro';
const money = p => Math.round(Number(p || 0) / 100);

export default function CareerGamesPaymentPanel({ currentUser, onBack, onVerified }) {
  const [quote,setQuote]=useState(null); const [loading,setLoading]=useState(true); const [paying,setPaying]=useState(false); const [error,setError]=useState(''); const [scriptReady,setScriptReady]=useState(false);
  useEffect(()=>{(async()=>{try{const user=currentUser||auth.currentUser;if(!user)throw new Error('Please sign in again.');const token=await user.getIdToken();const r=await fetch('/api/career/quote',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({product:PRODUCT})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to load pricing.');setQuote(d);}catch(e){setError(e.message||'Unable to load pricing.');}finally{setLoading(false);}})();},[currentUser]);
  useEffect(()=>{if(typeof window==='undefined')return;if(window.Razorpay){setScriptReady(true);return;}const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.async=true;s.onload=()=>setScriptReady(true);s.onerror=()=>setError('Unable to load the payment gateway.');document.body.appendChild(s);},[]);
  const pay=async()=>{setPaying(true);setError('');try{const user=currentUser||auth.currentUser;if(!user)throw new Error('Please sign in again.');const token=await user.getIdToken();const r=await fetch('/api/career/create-order',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({product:PRODUCT})});const order=await r.json();if(!r.ok)throw new Error(order?.error||'Unable to start payment.');if(order.sponsored){onVerified();return;}if(!scriptReady||!window.Razorpay)throw new Error('Payment gateway is still loading. Please try again.');const rz=new window.Razorpay({key:order.keyId,amount:order.amount,currency:order.currency||'INR',name:'VidyaVantage',description:'Games Pro Pass',order_id:order.orderId,prefill:{name:user.displayName||'',email:user.email||''},theme:{color:'#4f46e5'},handler:async response=>{try{const verifyToken=await user.getIdToken(true);const vr=await fetch('/api/career/verify-payment',{method:'POST',headers:{Authorization:`Bearer ${verifyToken}`,'Content-Type':'application/json'},body:JSON.stringify(response)});const data=await vr.json();if(!vr.ok||!data?.verified)throw new Error(data?.error||'Payment verification failed.');onVerified();}catch(e){setError(e.message||'Payment verification failed.');setPaying(false);}}});rz.on('payment.failed',x=>{setError(x?.error?.description||'Payment failed.');setPaying(false);});rz.open();}catch(e){setError(e.message||'Unable to start payment.');setPaying(false);}};
  const amount=money(quote?.amount||0);
  return <div style={{minHeight:'70vh',background:'#f8fafc',padding:'28px 24px 60px'}}><div style={{maxWidth:760,margin:'0 auto'}}><div style={{background:'#0f172a',color:'#fff',borderRadius:20,padding:'28px 30px'}}><div style={{fontSize:11,fontWeight:900,color:'#fbbf24',letterSpacing:1.5}}>VIDYAVANTAGE PLAYGROUND</div><h1 style={{margin:'6px 0'}}>Unlock Games Pro</h1><p style={{margin:0,color:'#cbd5e1'}}>Get the complete game library and deeper learning features.</p></div><div style={{...card,padding:30,marginTop:18}}><div style={{textAlign:'center'}}><div style={{fontSize:12,fontWeight:900,color:'#64748b'}}>ONE-TIME GAME PASS</div><div style={{fontSize:44,fontWeight:950,margin:'8px 0'}}>{loading?'Loading…':`₹${amount.toLocaleString('en-IN')}`}</div><div style={{color:'#64748b'}}>Full Games Pro access</div></div><div style={{display:'grid',gap:9,margin:'24px 0'}}>{['Unlimited game sessions','More levels and difficulty options','Career-themed game content','Private progress and mastery insights','Full Career Quest library','No public leaderboards or punitive streaks'].map(x=><div key={x} style={{padding:12,borderRadius:10,background:'#f8fafc',fontWeight:800,color:'#334155'}}>✓ {x}</div>)}</div>{error&&<div style={{padding:12,borderRadius:10,background:'#fef2f2',color:'#991b1b',fontWeight:700,marginBottom:12}}>{error}</div>}<button onClick={pay} disabled={loading||paying||!quote} style={{width:'100%',border:0,borderRadius:12,padding:16,background:paying?'#94a3b8':'linear-gradient(135deg,#4f46e5,#7c3aed)',color:'#fff',fontWeight:900,fontSize:16}}>{paying?'Processing…':amount===0?'Unlock — Sponsored':`Pay ₹${amount.toLocaleString('en-IN')} & Unlock`}</button><button onClick={onBack} disabled={paying} style={{width:'100%',border:0,background:'transparent',padding:12,marginTop:7,color:'#64748b',fontWeight:800}}>← Back to Games</button></div></div></div>;
}
const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18};
