import crypto from 'crypto';
import { requireSuperAdmin, sendAuthorizationFailure } from '../../../../src/security/adminAuthorization.js';
import { getAdminFirestore } from '../../../../src/security/firebaseAdmin.js';

export default async function handler(req,res){
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed.'});
  const authorization=await requireSuperAdmin(req);if(sendAuthorizationFailure(res,authorization))return;
  try{
    const{db,decodedToken}=authorization;const{razorpay_order_id:orderId,razorpay_payment_id:paymentId,razorpay_signature:signature}=req.body||{};if(!orderId||!paymentId||!signature)return res.status(400).json({error:'Incomplete payment verification data.'});
    const paymentRef=db.collection('institutionPayments').doc(orderId);const paymentSnap=await paymentRef.get();if(!paymentSnap.exists)return res.status(404).json({error:'Institution payment order was not created by Secret Sharz.'});const paymentRecord=paymentSnap.data();
    if(paymentRecord.status==='captured')return res.status(200).json({verified:true,access:'entitled',institutionId:paymentRecord.institutionId,orderId,paymentId:paymentRecord.paymentId||paymentId});
    const keyId=process.env.RAZORPAY_KEY_ID,keySecret=process.env.RAZORPAY_KEY_SECRET;if(!keyId||!keySecret)return res.status(503).json({error:'Payment gateway is not configured yet.'});
    const expected=crypto.createHmac('sha256',keySecret).update(`${orderId}|${paymentId}`).digest('hex');const provided=Buffer.from(String(signature));const expectedBuffer=Buffer.from(expected);if(provided.length!==expectedBuffer.length||!crypto.timingSafeEqual(provided,expectedBuffer))return res.status(400).json({error:'Payment signature verification failed.'});
    const authHeader=Buffer.from(`${keyId}:${keySecret}`).toString('base64');const orderResponse=await fetch(`https://api.razorpay.com/v1/orders/${encodeURIComponent(orderId)}`,{headers:{Authorization:`Basic ${authHeader}`}});const order=await orderResponse.json();if(!orderResponse.ok)return res.status(502).json({error:'Unable to verify the institution order with Razorpay.'});
    if(order.id!==orderId||order.currency!=='INR'||Number(order.amount)!==Number(paymentRecord.amountPaise))return res.status(400).json({error:'Institution payment amount does not match the recorded entitlement.'});if(order.notes?.institutionId!==paymentRecord.institutionId)return res.status(403).json({error:'Payment order is not associated with this institution.'});
    const paymentResponse=await fetch(`https://api.razorpay.com/v1/payments/${encodeURIComponent(paymentId)}`,{headers:{Authorization:`Basic ${authHeader}`}});const payment=await paymentResponse.json();if(!paymentResponse.ok)return res.status(502).json({error:'Unable to verify the institution payment with Razorpay.'});if(payment.order_id!==orderId||payment.currency!=='INR'||Number(payment.amount)!==Number(paymentRecord.amountPaise))return res.status(400).json({error:'Institution payment details do not match the entitlement.'});if(String(payment.status)!=='captured')return res.status(400).json({error:'Institution payment has not been captured.'});
    const now=new Date().toISOString();await db.runTransaction(async transaction=>{const freshPayment=await transaction.get(paymentRef);if(!freshPayment.exists)throw Object.assign(new Error('Institution payment record disappeared.'),{status:404});const fresh=freshPayment.data();if(fresh.status==='captured')return;const institutionRef=db.collection('institutions').doc(fresh.institutionId);const institutionSnap=await transaction.get(institutionRef);if(!institutionSnap.exists)throw Object.assign(new Error('Institution not found.'),{status:404});const existingInstitution=institutionSnap.data();transaction.update(paymentRef,{status:'captured',paymentId,capturedAt:now,verifiedBy:decodedToken.uid,updatedAt:now});transaction.set(institutionRef,{status:'active',licenses:{...(existingInstitution.licenses||{}),paymentStatus:'paid',paidAt:now,paidBy:decodedToken.uid,paidAmount:Number(payment.amount)/100,paidAmountPaise:Number(payment.amount),currency:payment.currency,paymentOrderId:orderId,paymentId},updatedAt:now},{merge:true});transaction.set(db.collection('adminAuditLogs').doc(),{action:'institution.payment_captured',resource:'institution',resourceId:fresh.institutionId,actorUid:decodedToken.uid,actorEmail:decodedToken.email||null,details:{orderId,paymentId,amountPaise:Number(payment.amount),licenseCount:Number(fresh.licenseCount||0)},createdAt:now});});
    return res.status(200).json({verified:true,access:'entitled',institutionId:paymentRecord.institutionId,orderId,paymentId});
  }catch(error){return res.status(error.status||500).json({error:error.message||'Institution payment verification failed.'});}
}
