import React,{useEffect,useState} from 'react';
import {auth} from '../../../src/firebase';

export default function CareerPaymentV2(){
 const[ready,setReady]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[quote,setQuote]=useState({amount:null,bundleTitle:'Full Career Intelligence Test Bundle',bundleId:null});
 useEffect(()=>{if(typeof window==='undefined')return;try{const bundleId=localStorage.getItem('vv_selected_bundle_id');setQuote(q=>({...q,bundleId}));}catch(_){}if(window.Razorpay){setReady(true);return;}const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.async=true;s.onload=()=>setReady(true);s.onerror=()=>setError('Unable to load payment gateway.');document.body.appendChild(s);},[]);
 const pay=async()=>{setBusy(true);setError('');try{const u=auth.currentUser;if(!u)throw new Error('Please sign in again.');if(!ready||!window.Razorpay)throw new Error('Payment gateway is still loading.');const token=await u.getIdToken();const r=await fetch('/api/career/create-order-v2',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({productKey:'student_individual',bundleId:quote.bundleId||undefined})});const order=await r.json();if(!r.ok)throw new Error(order?.error||'Unable to create payment order.');setQuote({amount:order.amount,bundleTitle:order.bundleTitle||quote.bundleTitle,bundleId:order.bundleId});const rz=new window.Razorpay({key:order.keyId,amount:order.amount,currency:'INR',name:'VidyaVantage',description:order.bundleTitle||'Full Career Intelligence Report',order_id:order.orderId,prefill:{name:u.displayName||'',email:u.email||''},theme:{color:'#4f46e5'},handler:async(response)=>{try{const fresh=await u.getIdToken(true);const vr=await fetch('/api/career/verify-payment',{method:'POST',headers:{Authorization:`Bearer ${fresh}`,'Content-Type':'application/json'},body:JSON.stringify(response)});const d=await vr.json();if(!vr.ok||!d.verified)throw new Error(d?.error||'Payment verification failed.');window.location.href='/dashboard/career/report-v2';}catch(e){setError(e.message||'Payment verification failed.');setBusy(false);}}});rz.on('payment.failed',r=>{setError(r?.error?.description||'Payment failed.');setBusy(false);});rz.open();}catch(e){setError(e.message||'Unable to start payment.');setBusy(false);}};
 const displayAmount=quote.amount==null?'Configured at checkout':`₹${Math.round(quote.amount/100).toLocaleString('en-IN')}`;
 return <div style={{minHeight:'100vh',background:'#f8fafc',display:'grid',placeItems:'center',padding:20}}><div style={{maxWidth:680,width:'100%',background:'#fff',border:'1px solid #e2e8f0',borderRadius:20,padding:32,boxShadow:'0 10px 35px rgba(15,23,42,.07)'}}><div style={{color:'#4f46e5',fontSize:11,fontWeight:900,letterSpacing:1.5}}>VIDYAVANTAGE · PREMIUM CAREER INTELLIGENCE</div><h1 style={{margin:'8px 0'}}>Unlock your 20-page Career Intelligence Report</h1><div style={{fontSize:38,fontWeight:950}}>{displayAmount}</div><p style={{color:'#64748b',lineHeight:1.7}}>Your selected assessment bundle is interpreted as one integrated Career Intelligence report. Institutional licence holders do not purchase this separately.</p><div style={{padding:14,background:'#f8fafc',borderRadius:12,fontWeight:850,color:'#334155',marginBottom:18}}>Selected bundle: {quote.bundleTitle}</div><div style={{display:'grid',gap:9,margin:'20px 0'}}>{['Detailed interpretation of the tests you selected','Career context and developmental interpretation','Career clusters, directions and alternative pathways','Education and skills roadmap','Action plan and practical next steps','Printable 20-page premium report'].map(x=><div key={x} style={{padding:12,background:'#f8fafc',borderRadius:9,fontWeight:700,color:'#334155'}}>✓ {x}</div>)}</div>{error&&<div style={{padding:12,background:'#fef2f2',color:'#991b1b',borderRadius:9,fontWeight:700,marginBottom:12}}>{error}</div>}<button onClick={pay} disabled={busy} style={{width:'100%',border:0,borderRadius:11,padding:15,background:busy?'#94a3b8':'linear-gradient(135deg,#4f46e5,#7c3aed)',color:'#fff',fontWeight:900,fontSize:15,cursor:'pointer'}}>{busy?'Processing…':'Continue to Secure Payment'}</button><button onClick={()=>window.history.back()} style={{width:'100%',border:0,background:'transparent',padding:12,color:'#64748b',fontWeight:800,cursor:'pointer'}}>← Back</button></div></div>
}
