// Academic context is guidance context, not psychometric evidence.
// Curriculum catalogues are versioned separately from assessment scoring.
export const ACADEMIC_CONTEXT_VERSION='2026.2';
export const SCHOOL_STAGES=Object.freeze([{id:'nursery',label:'Pre-school / Nursery',typicalAgeMin:3,typicalAgeMax:4,level:0},{id:'lkg',label:'LKG',typicalAgeMin:4,typicalAgeMax:5,level:0},{id:'ukg',label:'UKG',typicalAgeMin:5,typicalAgeMax:6,level:0},...Array.from({length:12},(_,i)=>({id:`grade_${i+1}`,label:`Class ${i+1}`,typicalAgeMin:i+6,typicalAgeMax:i+7,level:i+1}))]);
export const BOARD_OPTIONS=Object.freeze([{id:'cbse',label:'CBSE'},{id:'cicse',label:'CISCE / ICSE / ISC'},{id:'state_board',label:'State Board'},{id:'nios',label:'NIOS'},{id:'ib',label:'IB'},{id:'cambridge',label:'Cambridge / IGCSE / A Levels'},{id:'other',label:'Other / International / School-specific'}]);
export const SENIOR_PATHWAYS=Object.freeze([{id:'science_pcm',label:'Science — Physics, Chemistry, Mathematics (PCM)'},{id:'science_pcb',label:'Science — Physics, Chemistry, Biology (PCB)'},{id:'science_pcmb',label:'Science — Physics, Chemistry, Mathematics, Biology (PCMB)'},{id:'science_computer',label:'Science — Computer Science / Informatics-oriented'},{id:'commerce',label:'Commerce'},{id:'humanities_arts',label:'Humanities / Arts'},{id:'vocational_school',label:'School-based Vocational / Skill pathway'},{id:'iti',label:'ITI / Craftsmen Training Scheme (CTS)'},{id:'diploma_polytechnic',label:'Diploma / Polytechnic'},{id:'nios_vocational',label:'NIOS Academic / Vocational'},{id:'other',label:'Other / Mixed subject combination'}]);
export const CBSE_SENIOR_ACADEMIC_SUBJECTS=Object.freeze(['Accountancy','Applied Mathematics','Biology','Biotechnology','Business Studies','Carnatic Melodic Music','Carnatic Percussion Music','Carnatic Vocal Music','Chemistry','Computer Science','Dance','Economics','Engineering Graphics','Entrepreneurship','Fine Arts','Geography','Hindustani Melodic Music','Hindustani Percussion Music','Hindustani Vocal Music','History','Home Science','Knowledge Traditions & Practices of India','Legal Studies','Mathematics','NCC','Physical Education','Physics','Political Science','Psychology','Sociology','Informatics Practices','Creative Writing / Translation Studies','Fashion Studies','Other CBSE academic elective']);
export const CBSE_SECONDARY_SKILL_SUBJECTS=Object.freeze(['Retail (401)','Information Technology (402)','Security (403)','Automotive (404)','Introduction to Financial Markets (405)','Introduction to Tourism (406)','Beauty & Wellness (407)','Agriculture (408)','Food Production (409)','Front Office Operations (410)','Banking & Insurance (411)','Marketing & Sales (412)','Healthcare (413)','Apparel (414)','Multi-Media / Media (415)','Multi Skill Foundation Course (416)','Artificial Intelligence (417)','Physical Activity Trainer (418)','Data Science (419)','Electronics & Hardware (420)','Foundation Skills for Sciences — Pharmaceutical & Biotechnology (421)','Design Thinking (422)','Other CBSE Class IX-X skill subject']);
export const CBSE_SENIOR_SKILL_SUBJECTS=Object.freeze(['Retail (801)','Information Technology (802)','Web Application (803)','Automotive (804)','Financial Markets Management (805)','Tourism (806)','Beauty & Wellness (807)','Agriculture (808)','Food Production (809)','Front Office Operations (810)','Banking (811)','Marketing (812)','Health Care (813)','Insurance (814)','Horticulture (816)','Typography & Computer Application (817)','Geospatial Technology (818)','Electrical Technology (819)','Electronic Technology (820)','Multi-Media (821)','Taxation (822)','Cost Accounting (823)','Office Procedures & Practices (824)','Shorthand — English (825)','Shorthand — Hindi (826)','Air-conditioning & Refrigeration (827)','Medical Diagnostics (828)','Textile Design (829)','Design (830)','Salesmanship (831)','Business Administration (833)','Food Nutrition & Dietetics (834)','Mass Media Studies (835)','Library & Information Science (836)','Fashion Studies (837)','Yoga (841)','Early Childhood Care & Education (842)','Artificial Intelligence (843)','Data Science (844)','Physical Activity Trainer (845)','Land Transportation (846)','Electronics & Hardware (847)','Design Thinking & Innovation (848)','Other CBSE Class XI-XII skill subject']);
export const COMMON_SUBJECTS_BELOW_CLASS_11=Object.freeze(['English / first language','Second language','Third language','Mathematics','Science','Social Science','Computer / ICT','Art / Visual Arts','Music / Performing Arts','Physical Education','Health / Wellness','Skill / Vocational subject','Artificial Intelligence / Computational Thinking','Other school subject']);
export const ITI_PATHWAY_NOTE='ITI is a vocational training pathway, not a single school subject. DGT currently describes CTS as a national framework with 169 NSQF-compliant trades; the exact trade list should therefore be loaded from the current DGT catalogue rather than hard-coded as a fixed school-subject list.';
export const GRADE_MARK_RULES=Object.freeze({belowOrEqual10:{mode:'subject_performance_context',captureMarks:true,captureGrade:true},elevenOrAbove:{mode:'chosen_subject_pathway_context',captureMarks:true,captureGrade:true,captureSubjectChoice:true}});
export function normalizeGrade(value){if(value==null)return null;const raw=String(value).trim().toLowerCase().replace(/class|grade|standard/g,'').trim();const n=Number(raw);return Number.isInteger(n)&&n>=1&&n<=12?n:null;}
export function expectedStageFromAge(age){const n=Number(age);if(!Number.isFinite(n))return null;if(n>=3&&n<4)return'nursery';if(n>=4&&n<5)return'lkg';if(n>=5&&n<6)return'ukg';if(n>=6&&n<16)return`grade_${Math.floor(n-5)}`;if(n>=16&&n<18)return'grade_11';if(n>=18)return'grade_12';return null;}
export function ageGradeGuidance(age,declaredGrade){const grade=normalizeGrade(declaredGrade);const expected=expectedStageFromAge(age);return{declaredGrade:grade,ageExpectedStage:expected,ageExpectedGrade:expected?.startsWith('grade_')?Number(expected.split('_')[1]):null,ageGradeMismatch:Boolean(grade&&expected?.startsWith('grade_')&&Number(expected.split('_')[1])!==grade),ageGradeCheck:'soft_check_only'};}
export function getSubjectOptions({grade,board='cbse',pathway}={}){const g=normalizeGrade(grade);if(g==null)return[];if(g<=10)return board==='cbse'?[...COMMON_SUBJECTS_BELOW_CLASS_11,...CBSE_SECONDARY_SKILL_SUBJECTS]:[...COMMON_SUBJECTS_BELOW_CLASS_11,'Other board-specific subject'];if(pathway==='iti')return['ITI trade — select from current DGT/NCVT/SCVT catalogue'];if(board==='cbse')return[...CBSE_SENIOR_ACADEMIC_SUBJECTS,...CBSE_SENIOR_SKILL_SUBJECTS];return['Language / first subject','Language / second subject','Mathematics','Physics','Chemistry','Biology','Computer Science / Informatics','Economics','Accountancy','Business Studies','History','Geography','Political Science','Psychology','Sociology','Fine Arts / Performing Arts','Physical Education','Vocational / Skill subject','Other board-specific subject'];}
export function subjectPerformanceInterpretation({subject,marks,grade,goal}={}){const score=Number(marks);const hasScore=Number.isFinite(score)&&score>=0&&score<=100;if(!hasScore)return{status:'no_valid_mark',message:null,goalPath:'not_evaluated'};const g=normalizeGrade(grade);if(g&&g>=11)return{status:'senior_secondary_context_only',message:'Subject performance should inform feasibility and support planning; it must not be used as a psychometric score.',goalPath:goal?'compare_goal_with_subject_and_pathway':'explore_pathways'};if(score>=75)return{status:'strong',message:`${subject||'This subject'} is currently a relative strength. Use it as one piece of evidence when exploring related pathways.`,goalPath:goal?'support_goal_and_build_on_strength':'explore_related_pathways'};if(score>=50)return{status:'developing',message:`${subject||'This subject'} is developing. A lower mark should be explored for causes before treating it as a barrier.`,goalPath:goal?'support_goal_with_skill_building':'explore_and_test_options'};return{status:'needs_support',message:`${subject||'This subject'} is currently a lower-performing area. Do not rule out a goal from marks alone; identify the cause, provide targeted support, and consider an alternative route if the barrier persists.`,goalPath:goal?'goal_plus_support_plus_alternative':'support_then_explore'};}
export function buildAcademicDecisionContext({age,grade,board,stream,subjects=[],subjectMarks={},goal}={}){const ageGrade=ageGradeGuidance(age,grade);const normalizedGrade=ageGrade.declaredGrade;const level=normalizedGrade==null?null:normalizedGrade<=10?'secondary_or_below':'senior_secondary_or_above';const performance=Object.entries(subjectMarks||{}).map(([subject,marks])=>({subject,marks,...subjectPerformanceInterpretation({subject,marks,grade:normalizedGrade,goal})}));return{version:ACADEMIC_CONTEXT_VERSION,age:Number.isFinite(Number(age))?Number(age):null,grade:normalizedGrade,board:board||null,stream:stream||null,subjects:[...new Set((subjects||[]).filter(Boolean))],level,ageGrade,subjectPerformance:performance,goal:goal||null,subjectOptions:getSubjectOptions({grade:normalizedGrade,board,pathway:stream}),decisionRule:level==='senior_secondary_or_above'?'honour_chosen_subject_pathway_and_goal':'use_subject_performance_as_context_and_build_a_supportive_goal_path'};}
