import React, { useEffect, useState } from 'react';
import { auth } from '../../firebase';
import { CreditCard, RefreshCw, ShieldCheck } from 'lucide-react';

function money(value){return `₹${Number(value||0).toLocaleString('en-IN')}`;}

export default function InstitutionPaymentsTab(){
  const [institutions,setInstitutions]=useState([]);const[loading,setLoading]=useState(true);const[paying,setPaying]=useState('');const[error,setError]=useState('');const[message,setMessage]=useState('');const[scriptReady,setScriptReady]=useState(false);
  const load=async()=>{try{setLoading(true);setError('');const user=auth.currentUser;if(!user)throw new Error('Authentication required.');const token=await user.getIdToken(true);const response=await fetch('/api/admin/institutions',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load institutions.');setInstitutions(data.institutions||[]);}catch(err){setError(err.message||'Unable to load institutions.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(typeof window==='undefined')return undefined;if(window.Razorpay){setScriptReady(true);return undefined;}const existing=document.querySelector('script[data-razorpay-checkout]');if(existing){const handleLoad=()=>setScriptReady(true);existing.addEventListener('load',handleLoad);return()=>existing.removeEventListener('load',handleLoad);}const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;script.dataset.razorpayCheckout='true';script.onload=()=>setScriptReady(true);script.onerror=()=>setError('Unable to load Razorpay checkout.');document.body.appendChild(script);return()=>{};},[]);
  const pay=async institution=>{try{setPaying(institution.id);setError('');setMessage('');const user=auth.currentUser;if(!user)throw new Error('Authentication required.');const token=await user.getIdToken(true);const orderResponse=await fetch('/api/admin/institutions/payment-order',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({institutionId:institution.id})});const order=await orderResponse.json();if(!orderResponse.ok)throw new Error(order.error||'Unable to create institution payment order.');if(order.sponsored){setMessage(`${institution.name} entitlement activated.`);await load();return;}if(!scriptReady||!window.Razorpay)throw new Error('Razorpay checkout is still loading.');const checkout=new window.Razorpay({key:order.keyId,amount:order.amount,currency:order.currency||'INR',name:'Secret Sharz',description:`${institution.name} · ${order.licenseCount} career assessment licenses`,order_id:order.orderId,prefill:{name:institution.contactPerson||'',email:institution.contactEmail||''},theme:{color:'#059669'},modal:{ondismiss:()=>setPaying('')},handler:async response=>{try{const verifyToken=await user.getIdToken(true);const verifyResponse=await fetch('/api/admin/institutions/verify-payment',{method:'POST',headers:{Authorization:`Bearer ${verifyToken}`,'Content-Type':'application/json'},body:JSON.stringify(response)});const verification=await verifyResponse.json();if(!verifyResponse.ok||!verification.verified)throw new Error(verification.error||'Payment could not be verified.');setMessage(`${institution.name} entitlement is now active.`);await load();}catch(err){setError(err.message||'Institution payment verification failed.');}finally{setPaying('');}}});checkout.on('payment.failed',response=>{setError(response?.error?.description||'Institution payment failed.');setPaying('');});checkout.open();}catch(err){setError(err.message||'Unable to start institution payment.');setPaying('');}};
  return <div className="max-w-6xl mx-auto space-y-6"><div className="flex items-center justify-between gap-4"><div><h3 className="text-2xl font-bold text-slate-900">Institution Payments</h3><p className="text-sm text-slate-500 mt-1">Collect and verify institutional assessment entitlement payments before student codes become usable.</p></div><button onClick={load} className="px-4 py-2.5 rounded-xl border border-slate-200 bg-white text-slate-700 font-semibold flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Refresh</button></div>{error&&<div className="px-4 py-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm font-semibold">{error}</div>}{message&&<div className="px-4 py-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm font-semibold">{message}</div>}<div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-4 border-b border-slate-100 flex items-center gap-3"><ShieldCheck className="w-5 h-5 text-emerald-600"/><div className="text-sm text-slate-600">Only a server-verified Razorpay capture changes an institution from pending to paid/active.</div></div>{loading?<div className="p-12 text-center text-slate-500">Loading institutional accounts...</div>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr><th className="text-left px-5 py-3">Institution</th><th className="text-left px-5 py-3">Licenses</th><th className="text-left px-5 py-3">Amount</th><th className="text-left px-5 py-3">Status</th><th className="text-right px-5 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{institutions.map(item=><tr key={item.id}><td className="px-5 py-4"><div className="font-black text-slate-900">{item.name}</div><div className="text-xs text-slate-400 mt-1">{item.institutionCode}</div></td><td className="px-5 py-4 font-semibold">{item.licenses.purchased}</td><td className="px-5 py-4 font-black">{money(item.licenses.totalAmount)}</td><td className="px-5 py-4"><span className={`px-2.5 py-1 rounded-full text-xs font-bold ${item.licenses.paymentStatus==='paid'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{item.licenses.paymentStatus}</span></td><td className="px-5 py-4 text-right">{item.licenses.paymentStatus==='paid'?<span className="text-emerald-700 font-bold inline-flex items-center gap-1"><ShieldCheck className="w-4 h-4"/>Entitled</span>:<button onClick={()=>pay(item)} disabled={Boolean(paying)} className="px-4 py-2 rounded-lg bg-emerald-600 text-white font-bold disabled:opacity-50 inline-flex items-center gap-2"><CreditCard className="w-4 h-4"/>{paying===item.id?'Opening…':'Collect Payment'}</button>}</td></tr>)}{!institutions.length&&<tr><td colSpan="5" className="px-5 py-10 text-center text-slate-500">No institutions found.</td></tr>}</tbody></table></div>}</div></div>;
}
