import React, { useEffect, useState } from 'react';
import { auth } from '../../firebase';

const GROUPS = {
  Students: ['student_free','student_individual','student_group_3','student_group_5','student_group_10'],
  'Working Professionals': ['professional_individual','professional_transition'],
  'HR / Employers': ['hr_employee'],
};

export default function PricingTab() {
  const [products, setProducts] = useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const load=async()=>{try{setLoading(true);const u=auth.currentUser;if(!u)throw new Error('Authentication required.');const t=await u.getIdToken(true);const r=await fetch('/api/admin/career-pricing',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load pricing.');setProducts(d.products||[]);}catch(e){setError(e.message||'Unable to load pricing.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const update=(key,patch)=>setProducts(p=>p.map(x=>x.key===key?{...x,...patch}:x));
  const save=async()=>{try{setSaving(true);setMessage('');setError('');const t=await auth.currentUser.getIdToken(true);const r=await fetch('/api/admin/career-pricing',{method:'PUT',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({products:products.map(p=>({key:p.key,amountPaise:Number(p.amountPaise)||0,active:p.active!==false}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save pricing.');setMessage('Pricing saved successfully.');await load();}catch(e){setError(e.message||'Unable to save pricing.');}finally{setSaving(false);}};
  if(loading)return <div className="flex items-center justify-center h-72 text-slate-500">Loading pricing catalogue...</div>;
  const map=Object.fromEntries(products.map(p=>[p.key,p]));
  return <div className="max-w-5xl mx-auto space-y-6"><div className="flex items-start justify-between gap-4"><div><h3 className="text-2xl font-bold text-slate-900">Pricing & Products</h3><p className="text-sm text-slate-500 mt-1">Change base prices without changing application code.</p></div><button onClick={save} disabled={saving} className="px-5 py-2.5 rounded-xl bg-emerald-600 text-white font-semibold disabled:opacity-50">{saving?'Saving...':'Save Changes'}</button></div>{message&&<div className="px-4 py-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-sm">{message}</div>}{error&&<div className="px-4 py-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">{error}</div>}<div className="p-4 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900 text-sm">Institutional negotiated pricing and coupons will be separate from these default products.</div>{Object.entries(GROUPS).map(([group,keys])=><section key={group} className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div className="px-5 py-4 border-b border-slate-100"><h4 className="font-bold text-slate-900">{group}</h4></div><div className="divide-y divide-slate-100">{keys.map(k=>{const p=map[k];if(!p)return null;return <div key={k} className="px-5 py-4 flex flex-col md:flex-row md:items-center gap-4"><div className="flex-1"><p className="font-semibold text-slate-900">{p.label}</p><p className="text-xs text-slate-400 mt-1">{p.sku} · {p.reportTier}{p.seats?` · ${p.seats} seats`:''}</p></div><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={p.active!==false} onChange={e=>update(k,{active:e.target.checked})}/>Active</label><div className="flex items-center gap-2"><span>₹</span><input type="number" min="0" value={Math.round(Number(p.amountPaise||0)/100)} onChange={e=>update(k,{amountPaise:Math.max(0,Math.round(Number(e.target.value||0)*100))})} className="w-32 px-3 py-2 rounded-lg border border-slate-200 text-right font-semibold"/></div></div>})}</div></section>)}</div>;
}
