import React, { useState, useEffect } from 'react';
import { signOut } from 'firebase/auth';
import { auth } from '../../firebase';
import AdminSidebar from './AdminSidebar';
import OverviewTab from './OverviewTab';
import StudentDirectoryTab from './StudentDirectoryTab';
import InstitutionDirectoryTab from './InstitutionDirectoryTab';
import InstitutionServicesTab from './InstitutionServicesTab';
import InstitutionPaymentsTab from './InstitutionPaymentsTab';
import ProfessionalDirectoryTab from './ProfessionalDirectoryTab';
import ParentDirectoryTab from './ParentDirectoryTab';
import SystemSettingsTab from './SystemSettingsTab';
import PricingTab from './PricingTab';
import CareerOffersTab from './CareerOffersTab';

const FALLBACK_STATS={totalUsers:{value:0,change:null,trend:'up',changeLabel:'live total'},recentSessions:{value:0,change:null,trend:'up',changeLabel:'sessions · 7d'},pendingIEPs:{value:0,change:null,trend:'up',changeLabel:'live total'},completedAssessments:{value:0,change:null,trend:'up',changeLabel:'live total'}};
const SuperAdminView=({user,userData,onBackToApp})=>{const[activeTab,setActiveTab]=useState('overview');const[isLoading,setIsLoading]=useState(true);const[overviewData,setOverviewData]=useState({stats:FALLBACK_STATS,counts:{},pathDistribution:[],engagementData:[],limitations:{}});const[overviewError,setOverviewError]=useState('');
useEffect(()=>{let mounted=true;(async()=>{try{setIsLoading(true);setOverviewError('');const current=auth.currentUser||user;if(!current)throw new Error('Authentication required.');let token=await current.getIdToken(true);let r=await fetch('/api/admin/overview-stats',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(r.status===401){token=await current.getIdToken(true);r=await fetch('/api/admin/overview-stats',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});}const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load overview statistics.');if(mounted)setOverviewData(p);}catch(e){if(mounted){setOverviewError(e?.message||'Unable to load live overview data.');setOverviewData(x=>({...x,stats:FALLBACK_STATS}));}}finally{if(mounted)setIsLoading(false);}})();return()=>{mounted=false;};},[user]);
const logout=async()=>{try{await signOut(auth);if(onBackToApp)onBackToApp();}catch(e){console.error('Logout failed:',e);}};
const content=()=>{if(isLoading&&activeTab==='overview')return <div className="flex flex-col items-center justify-center h-96"><div className="w-12 h-12 border-4 border-emerald-200 border-t-emerald-500 rounded-full animate-spin mb-4"/><p className="text-slate-500 font-medium">Loading live platform data...</p></div>;switch(activeTab){case'overview':return <>{overviewError&&<div className="mb-4 px-4 py-3 rounded-xl border border-amber-200 bg-amber-50 text-amber-800 text-sm font-medium">{overviewError}</div>}<OverviewTab data={overviewData}/></>;case'students':return <StudentDirectoryTab/>;case'institutions':return <InstitutionDirectoryTab/>;case'institutionServices':return <InstitutionServicesTab/>;case'institutionPayments':return <InstitutionPaymentsTab/>;case'professionals':return <ProfessionalDirectoryTab/>;case'parents':return <ParentDirectoryTab/>;case'pricing':return <PricingTab/>;case'offers':return <CareerOffersTab/>;case'settings':return <SystemSettingsTab/>;default:return <OverviewTab data={overviewData}/>;}};
return <div className="flex h-screen w-full bg-slate-50 overflow-hidden"><AdminSidebar activeTab={activeTab} onTabChange={setActiveTab} user={user} onLogout={logout}/><div className="flex-1 flex flex-col overflow-hidden"><header className="h-16 bg-white border-b border-slate-100 px-6 flex items-center justify-between shadow-sm"><div className="flex items-center gap-4"><h2 className="text-lg font-bold text-slate-900 capitalize">{activeTab.replace('_',' ')}</h2><span className="px-2 py-1 bg-slate-100 rounded-lg text-xs font-semibold text-slate-600">{userData?.role||'super_admin'}</span></div><button onClick={onBackToApp} className="px-4 py-2 text-sm font-semibold text-slate-600 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg">Back to App</button></div><main className="flex-1 overflow-y-auto p-6">{content()}</main></div></div>};
export default SuperAdminView;
