import React, { useState, useEffect } from 'react';
import { signOut } from 'firebase/auth';
import { auth } from '../../firebase';
import AdminSidebar from './AdminSidebar';
import OverviewTab from './OverviewTab';
import StudentDirectoryTab from './StudentDirectoryTab';
import InstitutionDirectoryTab from './InstitutionDirectoryTab';
import InstitutionServicesTab from './InstitutionServicesTab';
import InstitutionPaymentsTab from './InstitutionPaymentsTab';
import ProfessionalDirectoryTab from './ProfessionalDirectoryTab';
import ParentDirectoryTab from './ParentDirectoryTab';
import SystemSettingsTab from './SystemSettingsTab';
import PricingTab from './PricingTab';
import CareerOffersTab from './CareerOffersTab';

const FALLBACK_STATS={totalUsers:{value:0,change:null,trend:'up',changeLabel:'live total'},recentSessions:{value:0,change:null,trend:'up',changeLabel:'sessions · 7d'},pendingIEPs:{value:0,change:null,trend:'up',changeLabel:'live total'},completedAssessments:{value:0,change:null,trend:'up',changeLabel:'live total'}};
const SERVICE_LABELS={careerStudents:'Career · Students',careerParents:'Career · Parents',careerInstitutions:'Career · Institutions',wellbeingStudents:'Wellbeing · Students',wellbeingParents:'Wellbeing · Parents',wellbeingInstitutions:'Wellbeing · Institutions',senStudents:'SEN · Students',senParents:'SEN · Parents',senInstitutions:'SEN · Institutions'};

const ServiceView=({label,kind,theme})=><div className="space-y-5"><div><p className={`text-xs font-semibold uppercase tracking-[0.14em] ${theme==='dark'?'text-slate-500':'text-slate-400'}`}>Service workspace</p><h1 className={`mt-1 text-2xl font-bold tracking-tight ${theme==='dark'?'text-white':'text-slate-950'}`}>{label}</h1><p className={`mt-1 text-sm ${theme==='dark'?'text-slate-400':'text-slate-500'}`}>A service-specific administrative view. Detailed controls will use the existing canonical directory and entitlement modules rather than duplicate records.</p></div><div className={`rounded-2xl border p-6 ${theme==='dark'?'bg-[#111827] border-slate-800':'bg-white border-slate-200 shadow-sm'}`}><div className="flex items-start gap-4"><div className="w-11 h-11 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-500"><span className="text-lg font-bold">{kind==='student'?'S':kind==='parent'?'P':'I'}</span></div><div><h2 className={`font-bold ${theme==='dark'?'text-white':'text-slate-900'}`}>{kind==='student'?'Student cohort':kind==='parent'?'Parent cohort':'Institution cohort'}</h2><p className={`mt-1 text-sm leading-6 ${theme==='dark'?'text-slate-400':'text-slate-500'}`}>This workspace is connected to Secret Sharz's central identity and service-entitlement model. No duplicate user records are created here.</p></div></div></div></div>;

const SuperAdminView=({user,userData,onBackToApp})=>{
 const[activeTab,setActiveTab]=useState('overview');const[isLoading,setIsLoading]=useState(true);const[overviewData,setOverviewData]=useState({stats:FALLBACK_STATS,counts:{},pathDistribution:[],engagementData:[],limitations:{}});const[overviewError,setOverviewError]=useState('');
 const[theme,setTheme]=useState(()=>{if(typeof window==='undefined')return'light';return window.localStorage.getItem('secretsharz_admin_theme')||'light';});
 useEffect(()=>{if(typeof window!=='undefined')window.localStorage.setItem('secretsharz_admin_theme',theme);},[theme]);
 useEffect(()=>{let mounted=true;(async()=>{try{setIsLoading(true);setOverviewError('');const current=auth.currentUser||user;if(!current)throw new Error('Authentication required.');let token=await current.getIdToken(true);let r=await fetch('/api/admin/overview-stats',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(r.status===401){token=await current.getIdToken(true);r=await fetch('/api/admin/overview-stats',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});}const p=await r.json();if(!r.ok)throw new Error(p?.error||'Unable to load overview statistics.');if(mounted)setOverviewData(p);}catch(e){if(mounted){setOverviewError(e?.message||'Unable to load live overview data.');setOverviewData(x=>({...x,stats:FALLBACK_STATS}));}}finally{if(mounted)setIsLoading(false);}})();return()=>{mounted=false;};},[user]);
 const logout=async()=>{try{await signOut(auth);if(onBackToApp)onBackToApp();}catch(e){console.error('Logout failed:',e);}};
 const content=()=>{if(isLoading&&activeTab==='overview')return <div className="flex flex-col items-center justify-center h-96"><div className={`w-11 h-11 border-4 rounded-full animate-spin mb-4 ${theme==='dark'?'border-slate-700 border-t-emerald-400':'border-emerald-100 border-t-emerald-500'}`}/><p className={`font-medium ${theme==='dark'?'text-slate-400':'text-slate-500'}`}>Loading live platform data...</p></div>;
  if(SERVICE_LABELS[activeTab]){const kind=activeTab.includes('Students')?'student':activeTab.includes('Parents')?'parent':'institution';return <ServiceView label={SERVICE_LABELS[activeTab]} kind={kind} theme={theme}/>;}
  switch(activeTab){case'overview':return <OverviewTab data={overviewData} theme={theme}/>;case'students':return <StudentDirectoryTab/>;case'institutions':return <InstitutionDirectoryTab/>;case'institutionServices':return <InstitutionServicesTab/>;case'institutionPayments':return <InstitutionPaymentsTab/>;case'professionals':return <ProfessionalDirectoryTab/>;case'parents':return <ParentDirectoryTab/>;case'pricing':return <PricingTab/>;case'offers':return <CareerOffersTab/>;case'settings':return <SystemSettingsTab/>;default:return <OverviewTab data={overviewData} theme={theme}/>;}};
 return <div className={`ss-admin-root flex h-screen w-full overflow-hidden transition-colors duration-300 ${theme==='dark'?'ss-admin-theme-dark bg-[#080c16] text-white':'ss-admin-theme-light bg-[#f6f8fb] text-slate-900'}`}><style>{`.ss-admin-theme-dark .bg-white{background-color:#111827!important}.ss-admin-theme-dark .bg-slate-50{background-color:#0f172a!important}.ss-admin-theme-dark .bg-slate-100{background-color:#1e293b!important}.ss-admin-theme-dark .border-slate-100,.ss-admin-theme-dark .border-slate-200{border-color:#263244!important}.ss-admin-theme-dark .text-slate-900{color:#f8fafc!important}.ss-admin-theme-dark .text-slate-700{color:#e2e8f0!important}.ss-admin-theme-dark .text-slate-600{color:#cbd5e1!important}.ss-admin-theme-dark .text-slate-500{color:#94a3b8!important}.ss-admin-theme-dark .text-slate-400{color:#64748b!important}.ss-admin-theme-dark input,.ss-admin-theme-dark select,.ss-admin-theme-dark textarea{background-color:#0f172a!important;color:#f8fafc!important;border-color:#334155!important}.ss-admin-theme-dark .shadow-sm,.ss-admin-theme-dark .shadow-md{box-shadow:0 8px 30px rgba(0,0,0,.18)!important}`}</style><AdminSidebar activeTab={activeTab} onTabChange={setActiveTab} user={user} onLogout={logout} theme={theme} onToggleTheme={()=>setTheme(x=>x==='dark'?'light':'dark')}/><div className="flex-1 flex flex-col overflow-hidden"><header className={`h-[72px] shrink-0 px-7 flex items-center justify-between border-b transition-colors ${theme==='dark'?'bg-[#0b1020]/95 border-slate-800':'bg-white/95 border-slate-200'}`}><div><p className={`text-[10px] uppercase tracking-[0.16em] font-bold ${theme==='dark'?'text-slate-500':'text-slate-400'}`}>Secret Sharz · Admin Command Center</p><h2 className={`text-xl font-bold tracking-tight ${theme==='dark'?'text-white':'text-slate-950'}`}>{SERVICE_LABELS[activeTab]||({overview:'Platform Overview',professionals:'Professionals',institutions:'Institutions',institutionServices:'Service Entitlements',institutionPayments:'Revenue & Billing',students:'All Students',parents:'All Parents',pricing:'Pricing & Products',offers:'Offers & Coupons',settings:'System Settings'}[activeTab]||'Command Center')}</h2></div><div className="flex items-center gap-3"><div className={`hidden md:flex items-center gap-2 px-3 py-2 rounded-xl border text-xs font-semibold ${theme==='dark'?'border-slate-800 text-slate-400 bg-white/[0.02]':'border-slate-200 text-slate-500 bg-slate-50'}`}><span className="w-2 h-2 rounded-full bg-emerald-500"/>Secure admin session</div><button onClick={onBackToApp} className={`px-4 py-2.5 rounded-xl text-xs font-bold border transition-colors ${theme==='dark'?'border-slate-800 text-slate-300 hover:bg-white/5':'border-slate-200 text-slate-600 hover:bg-slate-50'}`}>Back to Secret Sharz</button></div></header><main className={`flex-1 overflow-y-auto p-5 md:p-7 ${theme==='dark'?'bg-[#080c16]':'bg-[#f6f8fb]'}`}>{content()}</main></div></div>;
};
export default SuperAdminView;
