import crypto from 'crypto';
import { requireSuperAdmin, sendAuthorizationFailure } from '../../../src/security/adminAuthorization.js';
import { getAdminAuth, getAdminFirestore } from '../../../src/security/firebaseAdmin.js';
import { calculateInstitutionPricing } from '../../../src/institution/institutionPricing.js';

function clean(value,max=200){return String(value||'').trim().slice(0,max);}
function slug(value){return clean(value,60).toUpperCase().replace(/[^A-Z0-9]+/g,'').slice(0,12)||'INSTITUTION';}
function institutionCode(name){return `SSZ-${slug(name)}-${String(new Date().getFullYear()).slice(-2)}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;}
function normaliseInstitution(doc){const data=doc.data();const licenses=data.licenses||{};const coordinator=data.coordinator||{};return{id:doc.id,name:data.name||'',institutionCode:data.institutionCode||data.tenantCode||'',tenantCode:data.tenantCode||'',status:data.status||'pending',address:data.address||'',contactPerson:data.contactPerson||'',contactEmail:data.contactEmail||'',contactPhone:data.contactPhone||'',coordinator:{uid:coordinator.uid||null,name:coordinator.name||data.contactPerson||'',email:coordinator.email||data.contactEmail||'',activatedAt:coordinator.activatedAt||null,role:coordinator.role||null,activated:Boolean(coordinator.uid)},createdAt:data.createdAt||null,updatedAt:data.updatedAt||null,licenses:{purchased:Number(licenses.purchased||0),used:Number(licenses.used||0),available:Number(licenses.available??Math.max(0,Number(licenses.purchased||0)-Number(licenses.used||0))),pricePerLicense:Number(licenses.pricePerLicense||0),discountType:licenses.discountType||'none',discountValue:Number(licenses.discountValue||0),discountAmount:Number(licenses.discountAmount||0),grossAmount:Number(licenses.grossAmount||0),totalAmount:Number(licenses.totalAmount||0),paymentStatus:licenses.paymentStatus||'pending'}};}
export default async function handler(req,res){if(!['GET','POST'].includes(req.method)){res.setHeader('Allow','GET, POST');return res.status(405).json({error:'Method not allowed.'});}const authorization=await requireSuperAdmin(req);if(sendAuthorizationFailure(res,authorization))return;try{const db=getAdminFirestore();const adminAuth=getAdminAuth();if(req.method==='GET'){const snapshot=await db.collection('institutions').orderBy('createdAt','desc').limit(1000).get();const institutions=snapshot.docs.map(normaliseInstitution);const totals=institutions.reduce((acc,institution)=>{acc.totalInstitutions+=1;acc.totalLicenses+=institution.licenses.purchased;acc.usedLicenses+=institution.licenses.used;acc.availableLicenses+=institution.licenses.available;if(institution.status==='active')acc.activeInstitutions+=1;if(institution.licenses.paymentStatus==='pending')acc.pendingPayments+=1;if(institution.coordinator.activated)acc.activeCoordinators+=1;return acc;},{totalInstitutions:0,activeInstitutions:0,totalLicenses:0,usedLicenses:0,availableLicenses:0,pendingPayments:0,activeCoordinators:0});return res.status(200).json({institutions,totals,generatedAt:new Date().toISOString()});}
const body=req.body||{};const name=clean(body.name);const contactEmail=clean(body.contactEmail,254).toLowerCase();const contactPerson=clean(body.contactPerson,160);if(!name)return res.status(400).json({error:'Institution name is required.'});if(!contactEmail||!/\S+@\S+\.\S+/.test(contactEmail))return res.status(400).json({error:'Coordinator email is required to create the institution account.'});const purchased=Number(body.licenseCount);if(!Number.isInteger(purchased)||purchased<1||purchased>100000)return res.status(400).json({error:'License count must be a whole number between 1 and 100,000.'});const pricing=calculateInstitutionPricing({licenseCount:purchased,pricePerLicense:body.pricePerLicense,discountType:body.discountType,discountValue:body.discountValue});const ref=db.collection('institutions').doc();const now=new Date().toISOString();const code=institutionCode(name);let authUser=null;let createdAuthUser=false;try{try{authUser=await adminAuth.getUserByEmail(contactEmail);const existingRole=authUser.customClaims?.role||null;if(existingRole&&existingRole!=='institution')return res.status(409).json({error:'The coordinator email is already assigned to another Secret Sharz role.'});const existingInstitutionId=authUser.customClaims?.institutionId||null;if(existingRole==='institution'&&existingInstitutionId)return res.status(409).json({error:'This coordinator account is already linked to an institution.'});const existingProfile=await db.collection('users').doc(authUser.uid).get();if(existingProfile.exists&&existingProfile.data()?.role&&existingProfile.data().role!=='institution')return res.status(409).json({error:'This email already belongs to an existing Secret Sharz user and cannot be converted into an institution account.'});}catch(error){if(error?.code!=='auth/user-not-found')throw error;authUser=await adminAuth.createUser({email:contactEmail,password:crypto.randomBytes(24).toString('base64url'),displayName:contactPerson||name,emailVerified:false,disabled:false});createdAuthUser=true;}
await adminAuth.setCustomUserClaims(authUser.uid,{...(authUser.customClaims||{}),role:'institution',institutionId:ref.id});
const record={id:ref.id,name,institutionCode:code,tenantCode:code.replace(/^SSZ-/,'').slice(0,20),status:body.status==='active'?'active':'pending',address:clean(body.address,500),contactPerson,contactEmail,contactPhone:clean(body.contactPhone,30),coordinator:{uid:authUser.uid,name:contactPerson||name,email:contactEmail,activatedAt:null,role:'institution'},licenses:{...pricing,used:0,available:purchased,paymentStatus:body.paymentStatus==='paid'?'paid':'pending',createdAt:now},createdAt:now,updatedAt:now};await ref.set(record);await db.collection('users').doc(authUser.uid).set({name:contactPerson||name,email:contactEmail,role:'institution',accountType:'institution',institutionId:ref.id,institutionName:name,profileComplete:true,updatedAt:now,...(createdAuthUser?{createdAt:now}:{} )},{merge:true});const activationLink=await adminAuth.generatePasswordResetLink(contactEmail);return res.status(201).json({institution:{...normaliseInstitution(await ref.get()),activationLink}});}catch(error){if(createdAuthUser&&authUser?.uid){try{await adminAuth.deleteUser(authUser.uid);}catch(cleanupError){console.error('[institutions] Auth cleanup failed:',cleanupError?.message||cleanupError);}}throw error;}}catch(error){return res.status(error.statusCode||500).json({error:error.message||'Unable to manage institutions.'});}}
