// Secret Sharz — First-class relationship storage (SERVER-ONLY).
// Relationships are an authorization primitive, not profile decoration.
import { createRelationshipRecord, isKnownValue, RELATIONSHIP_TYPES, SERVICE_DOMAINS, RELATIONSHIP_STATUSES } from '../platform/canonicalModel.js';
const COLLECTION = 'relationships';
function normalizeTimestamp(value) { if (value == null) return null; if (value instanceof Date) return value.toISOString(); if (typeof value === 'string' || typeof value === 'number') return value; return null; }
export function buildRelationshipDocument(input) { const record = createRelationshipRecord(input); return { ...record, authorizationBasis: input.authorizationBasis || null, startsAt: normalizeTimestamp(record.startsAt), endsAt: normalizeTimestamp(record.endsAt), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; }
export function validateRelationshipPatch(patch = {}) { if (patch.type !== undefined && !isKnownValue(patch.type, RELATIONSHIP_TYPES)) throw new Error('Unknown relationship type.'); if (patch.domain !== undefined && patch.domain !== null && !isKnownValue(patch.domain, SERVICE_DOMAINS)) throw new Error('Unknown service domain.'); if (patch.status !== undefined && !isKnownValue(patch.status, RELATIONSHIP_STATUSES)) throw new Error('Unknown relationship status.'); if (patch.authorizationBasis !== undefined && patch.authorizationBasis !== null && typeof patch.authorizationBasis !== 'string') throw new Error('Invalid authorization basis.'); if (patch.subjectPersonId !== undefined && !patch.subjectPersonId) throw new Error('subjectPersonId cannot be empty.'); if (patch.relatedPersonId !== undefined && !patch.relatedPersonId) throw new Error('relatedPersonId cannot be empty.'); if (patch.subjectPersonId && patch.relatedPersonId && patch.subjectPersonId === patch.relatedPersonId) throw new Error('A relationship cannot target the same person.'); return true; }
function activeRelationshipQuery(db, { subjectPersonId, type, domain = null }) { const query = db.collection(COLLECTION).where('subjectPersonId', '==', subjectPersonId).where('type', '==', type).where('status', '==', 'active').limit(50); return { query, domain }; }
export async function findActiveRelationships({ db, subjectPersonId, type, domain = null }) { if (!db) throw new Error('Firestore instance is required.'); if (!subjectPersonId || !type) return []; const { query } = activeRelationshipQuery(db, { subjectPersonId, type, domain }); const snapshot = await query.get(); return snapshot.docs.map(doc => ({ ref: doc.ref, id: doc.id, ...doc.data() })).filter(item => domain == null || item.domain == null || item.domain === domain); }
export async function createRelationship({ db, ...input }) { if (!db) throw new Error('Firestore instance is required.'); const document = buildRelationshipDocument(input); const ref = db.collection(COLLECTION).doc(); await ref.set({ ...document, relationshipId: ref.id }); return { id: ref.id, ...document, relationshipId: ref.id }; }
export async function createPendingRelationship({ db, ...input }) { return createRelationship({ db, ...input, status: 'pending', consentRequired: true, authorizationBasis: input.authorizationBasis || 'pending_guardian_acceptance' }); }
export async function ensurePendingRelationship({ db, subjectPersonId, relatedPersonId, type, domain = null, metadata = {} }) { if (!db) throw new Error('Firestore instance is required.'); validateRelationshipPatch({ subjectPersonId, relatedPersonId, type, domain }); const snapshot = await db.collection(COLLECTION).where('subjectPersonId', '==', subjectPersonId).where('relatedPersonId', '==', relatedPersonId).where('type', '==', type).limit(50).get(); const matches = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })); const active = matches.find(item => item.status === 'active'); if (active) return { ...active, existing: true }; const pending = matches.find(item => item.status === 'pending'); if (pending) return { ...pending, existing: true }; const blocked = matches.find(item => item.status === 'revoked' || item.status === 'suspended'); if (blocked) throw new Error('A suspended or revoked relationship requires an explicit administrative workflow.'); return createPendingRelationship({ db, subjectPersonId, relatedPersonId, type, domain, metadata }); }
export async function activateRelationship({ db, relationshipId, consentVerified = false, authorizationBasis = 'explicit_consent', activatedAt = new Date().toISOString() }) { if (!db) throw new Error('Firestore instance is required.'); if (!relationshipId) throw new Error('relationshipId is required.'); if (consentVerified !== true) throw new Error('Verified consent is required to activate this relationship.'); const ref = db.collection(COLLECTION).doc(relationshipId); let result = null; await db.runTransaction(async (tx) => { const snapshot = await tx.get(ref); if (!snapshot.exists) throw new Error('Relationship not found.'); const relationship = snapshot.data(); if (relationship.status === 'revoked' || relationship.status === 'ended' || relationship.status === 'suspended') throw new Error('Inactive relationship cannot be activated.'); if (relationship.consentRequired !== true) throw new Error('Relationship does not require consent; use an appropriate administrative transition.'); tx.update(ref, { status: 'active', authorizationBasis, startsAt: relationship.startsAt || activatedAt, updatedAt: activatedAt }); result = { id: relationshipId, ...relationship, status: 'active', authorizationBasis, startsAt: relationship.startsAt || activatedAt, updatedAt: activatedAt }; }); return result; }
export async function reassignRelationship({ db, subjectPersonId, relatedPersonId, type, domain = null, consentRequired = true, consentVerified = false, authorizationBasis = 'explicit_consent', startsAt = new Date().toISOString(), metadata = {} }) { if (!db) throw new Error('Firestore instance is required.'); validateRelationshipPatch({ subjectPersonId, relatedPersonId, type, domain, authorizationBasis }); if (consentRequired && consentVerified !== true) throw new Error('Verified consent is required for a consent-gated relationship assignment.'); let result = null; await db.runTransaction(async (tx) => { const { query } = activeRelationshipQuery(db, { subjectPersonId, type, domain }); const snapshot = await tx.get(query); const active = snapshot.docs.map(doc => ({ ref: doc.ref, id: doc.id, ...doc.data() })).filter(item => domain == null || item.domain == null || item.domain === domain); const conflicting = active.filter(item => item.relatedPersonId !== relatedPersonId); const now = new Date().toISOString(); for (const relationship of conflicting) tx.update(relationship.ref, { status: 'ended', endsAt: now, updatedAt: now }); const existingTarget = active.find(item => item.relatedPersonId === relatedPersonId); if (existingTarget) { result = { id: existingTarget.id, ...existingTarget, status: 'active', reassigned: conflicting.length > 0 }; return; } const document = buildRelationshipDocument({ subjectPersonId, relatedPersonId, type, domain, status: 'active', startsAt, endsAt: null, consentRequired, authorizationBasis }); const ref = db.collection(COLLECTION).doc(); tx.set(ref, { ...document, relationshipId: ref.id, metadata }); result = { id: ref.id, ...document, relationshipId: ref.id, metadata, reassigned: conflicting.length > 0 }; }); return result; }
export async function endRelationships({ db, subjectPersonId, type, domain = null, endsAt = new Date().toISOString(), endReason = 'ended' }) { if (!db) throw new Error('Firestore instance is required.'); validateRelationshipPatch({ subjectPersonId, type, domain }); let count = 0; await db.runTransaction(async (tx) => { const { query } = activeRelationshipQuery(db, { subjectPersonId, type, domain }); const snapshot = await tx.get(query); const active = snapshot.docs.map(doc => ({ ref: doc.ref, ...doc.data() })).filter(item => domain == null || item.domain == null || item.domain === domain); for (const relationship of active) tx.update(relationship.ref, { status: 'ended', endsAt, endReason, updatedAt: endsAt }); count = active.length; }); return count; }
export async function getActiveRelationship({ db, subjectPersonId, relatedPersonId, type, domain = null }) { if (!db) throw new Error('Firestore instance is required.'); if (!subjectPersonId || !relatedPersonId || !type) return null; const snapshot = await db.collection(COLLECTION).where('subjectPersonId', '==', subjectPersonId).where('relatedPersonId', '==', relatedPersonId).where('type', '==', type).where('status', '==', 'active').limit(20).get(); const matches = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })).filter(item => domain == null || item.domain == null || item.domain === domain); return matches[0] || null; }
export async function hasActiveRelationship({ db, subjectPersonId, relatedPersonId, types = [], domain = null }) { const allowedTypes = Array.isArray(types) ? types : [types]; for (const type of allowedTypes.filter(Boolean)) { const relationship = await getActiveRelationship({ db, subjectPersonId, relatedPersonId, type, domain }); if (relationship) return true; } return false; }
export const RELATIONSHIP_COLLECTION = COLLECTION;
