import React from 'react';
import { ASSESSMENT_MODULES, ASSESSMENT_BUNDLES } from './career/assessmentLibrary';

const card = { background: '#fff', border: '1px solid #e2e8f0', borderRadius: 18, padding: 22, boxShadow: '0 8px 28px rgba(15,23,42,.05)' };

export default function AssessmentLibraryView() {
  const full = ASSESSMENT_BUNDLES.find(bundle => bundle.id === 'full_career_intelligence');
  return <div style={{ minHeight: '100vh', background: '#f8fafc', padding: '30px 18px 70px' }}><div style={{ maxWidth: 1120, margin: '0 auto' }}>
    <section style={{ ...card, background: 'linear-gradient(135deg,#0f172a,#1e293b)', color: '#fff', padding: 30 }}><div style={{ color: '#fbbf24', fontSize: 11, fontWeight: 900, letterSpacing: 1.5 }}>VIDYAVANTAGE ASSESSMENT LIBRARY</div><h1 style={{ margin: '9px 0 7px', fontSize: 34 }}>Build a Career Intelligence Profile</h1><p style={{ margin: 0, color: '#cbd5e1', lineHeight: 1.75 }}>The platform uses separate assessment modules rather than one giant test. A valid module result can be reused across reports, upgrades and future career reviews.</p></section>
    <section style={{ ...card, marginTop: 16 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 18, flexWrap: 'wrap' }}><div><div style={{ color: '#4f46e5', fontSize: 11, fontWeight: 900, letterSpacing: 1.3 }}>FULL CAREER INTELLIGENCE</div><h2 style={{ margin: '6px 0' }}>Everything in one package</h2><p style={{ color: '#64748b', lineHeight: 1.7, marginBottom: 0 }}>For individual users, the complete ecosystem is presented as one package. Institutional licence holders receive the same complete experience through their institution entitlement.</p></div><div style={{ padding: '10px 14px', borderRadius: 10, background: '#eef2ff', color: '#4338ca', fontWeight: 900 }}>20-page report + full dashboard</div></div></section>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(240px,1fr))', gap: 14, marginTop: 16 }}>{ASSESSMENT_MODULES.map(module => <article key={module.id} style={{ ...card, position: 'relative' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}><h3 style={{ margin: 0, fontSize: 17 }}>{module.title}</h3>{module.status === 'catalogue' && <span style={{ fontSize: 10, fontWeight: 900, color: '#64748b' }}>SEPARATE MODULE</span>}</div><p style={{ color: '#64748b', lineHeight: 1.65, fontSize: 13 }}>{module.construct}</p><div style={{ padding: 10, borderRadius: 10, background: '#f8fafc', fontSize: 12, fontWeight: 800, color: '#334155' }}>Included in Full Career Intelligence</div>{module.note && <p style={{ color: '#94a3b8', fontSize: 11, lineHeight: 1.5, marginBottom: 0 }}>{module.note}</p>}</article>)}</div>
    <section style={{ ...card, marginTop: 16 }}><h2 style={{ marginTop: 0 }}>What Premium adds</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 10 }}>{['Career Fit + Job/Role Fit','Career Confidence + evidence','Alternative and exploratory careers','Non-linear pathway mapping','Stream and What-If scenarios','Skills and evidence roadmap','Affordability and friction analysis','College and education planning','Scholarship opportunities','Career Portfolio + Resume Builder','Career Journal + Goals','Parent Intelligence','Career Counsellor Review','Longitudinal reassessment history'].map(item => <div key={item} style={{ padding: 12, borderRadius: 10, background: '#f8fafc', fontWeight: 750, fontSize: 13 }}>✓ {item}</div>)}</div></section>
    <div style={{ display: 'flex', gap: 10, marginTop: 18, flexWrap: 'wrap' }}><button onClick={() => { window.location.href = '/dashboard/career/assessment'; }} style={{ border: 0, borderRadius: 11, padding: '13px 18px', background: '#4f46e5', color: '#fff', fontWeight: 900 }}>Start Career Assessment</button><button onClick={() => { window.location.href = '/dashboard/career'; }} style={{ border: '1px solid #cbd5e1', borderRadius: 11, padding: '13px 18px', background: '#fff', color: '#334155', fontWeight: 850 }}>Back to Career Dashboard</button></div>
  </div></div>;
}
