import React,{useEffect,useMemo,useState} from 'react';
import {auth,db} from './firebase';
import {doc,getDoc} from 'firebase/firestore';
import {getReportPages} from './career/reportArchitecture';

const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:26,boxShadow:'0 8px 28px rgba(15,23,42,.05)'};
const muted={color:'#64748b',lineHeight:1.75};
const val=(v,f='Not supplied')=>v===undefined||v===null||v===''?f:v;

function normalise(data){
 const a=data?.careerAssessmentV2;
 if(a)return {...a,profile:data,reportTier:'full'};
 const l=data?.careerAssessment||{}; const p=l.profile||{}; const code=l.hollandCode||data?.riasecCode||'';
 return {legacyAssessment:true,pathway:'student',profile:data,reportTier:'full',bundle:{title:'Legacy Career Discovery (RIASEC)'},answers:{},intake:{educationStage:p.dem_03||data?.educationStage||'',className:p.dem_03||data?.className||'',stream:l.streams?.[0]?.id||data?.recommendedStream||'',subjectsLiked:Array.isArray(p.dem_04)?p.dem_04.join(', '):''},scores:{riasecCode:Array.isArray(code)?code.join(''):String(code),riasec:l.riasecScores||data?.riasecScores||{},readinessPercent:Number(l.maturityPct??data?.maturityPct??0),big5:{},values:{},reasoning:{},environment:{}},careerExploration:l.top5Careers||data?.topCareerMatches||[]};
}

function NotAssessed(){return <div style={{padding:17,background:'#f8fafc',border:'1px dashed #cbd5e1',borderRadius:12,color:'#64748b'}}><strong>Not assessed in this attempt.</strong><div style={{marginTop:5}}>VidyaVantage will never manufacture a score or personality interpretation for a test family that was not included in the assessment.</div></div>}
function CareerList({items=[]}){return items.length?<div style={{display:'grid',gap:10}}>{items.slice(0,8).map((c,i)=><div key={i} style={{padding:15,background:'#f8fafc',borderRadius:12,border:'1px solid #eef2f7'}}><div style={{display:'flex',justifyContent:'space-between',gap:15}}><strong>{i+1}. {c.name||c.title}</strong>{c.matchScore!=null&&<strong style={{color:'#4f46e5'}}>{c.matchScore}%</strong>}</div><div style={{fontSize:12,color:'#64748b',marginTop:4}}>{c.stream||c.category||'Career direction'}</div>{c.desc&&<p style={{...muted,fontSize:13,margin:'7px 0 0'}}>{c.desc}</p>}</div>)}</div>:<NotAssessed/>}
function Content({id,r}){
 const s=r.scores||{},i=r.intake||{},careers=r.careerExploration||{}; const riasec=Object.entries(s.riasec||{}).sort((a,b)=>Number(b[1])-Number(a[1]));
 const not=<NotAssessed/>;
 switch(id){
 case'executive_snapshot':return <><p style={muted}>This report brings together the assessment evidence actually available on this account. It is exploratory guidance, not a diagnosis or prediction.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}><div style={{padding:15,background:'#f8fafc',borderRadius:12}}><b>Assessment</b><div>{val(r.bundle?.title)}</div></div><div style={{padding:15,background:'#f8fafc',borderRadius:12}}><b>RIASEC</b><div>{val(s.riasecCode,'—')}</div></div><div style={{padding:15,background:'#f8fafc',borderRadius:12}}><b>Readiness</b><div>{val(s.readinessPercent,'—')}%</div></div></div></>;
 case'interest_personality':return <><p style={muted}>Career interests are available below. Personality results are only interpreted when the Personality family was actually completed.</p><div style={{fontSize:40,fontWeight:950,letterSpacing:7,color:'#4f46e5'}}>{val(s.riasecCode,'—')}</div>{r.legacyAssessment&&not}</>;
 case'riasec_profile':return <>{riasec.length?riasec.map(([k,v])=><div key={k} style={{margin:'12px 0'}}><div style={{display:'flex',justifyContent:'space-between',fontWeight:800,fontSize:12}}><span>{k}</span><span>{v}%</span></div><div style={{height:9,background:'#e2e8f0',borderRadius:99,marginTop:5}}><div style={{width:`${Math.min(100,Number(v))}%`,height:'100%',background:'linear-gradient(90deg,#4f46e5,#7c3aed)',borderRadius:99}}/></div></div>):not}</>;
 case'career_directions':case'top_career_directions':case'target_roles':return <><p style={muted}>Career directions are exploration signals. They should be validated against eligibility, education requirements, evidence and real-world exposure.</p><CareerList items={careers}/></>;
 case'next_steps':case'action_roadmap':case'action_plan':return <><p style={muted}>Turn insight into evidence.</p><ol><li>Research two leading directions.</li><li>Verify current eligibility and prerequisite requirements.</li><li>Speak with one person doing the work.</li><li>Complete one small real-world project.</li><li>Record the next 30/60/90-day milestone.</li></ol></>;
 case'developmental_context':return <><p><b>Education stage:</b> {val(i.educationStage)}</p><p><b>Class / year:</b> {val(i.className)}</p><p><b>Stream:</b> {val(i.stream)}</p><p><b>Subjects:</b> {val(i.subjectsLiked)}</p><p><b>Academic average:</b> {val(i.academicAverage)}</p></>;
 case'stream_analysis':return <><p style={muted}>The stored assessment suggests the following stream direction. This is not a permanent boundary.</p><div style={{padding:18,background:'#eef2ff',borderRadius:12,fontWeight:900}}>Best fit: {val(i.stream)}</div></>;
 case'decision_readiness':return <><p style={muted}>The stored assessment includes a readiness/maturity signal.</p><div style={{fontSize:42,fontWeight:950}}>{val(s.readinessPercent,'—')}%</div></>;
 case'career_values':case'strengths_values':case'personality_profile':case'reasoning_profile':case'reasoning_skills':case'adaptability':case'work_environment':return not;
 case'alternative_careers':return careers?.length>3?<CareerList items={careers.slice(3)}/>:not;
 case'pathway_analysis':case'education_roadmap':case'skills_evidence':case'affordability':case'opportunity_plan':return <><p style={muted}>This section requires richer evidence than the stored RIASEC-only assessment contains. The architecture is present, but the system deliberately avoids inventing personalised pathway, skills, affordability or scholarship conclusions.</p>{not}</>;
 case'counsellor_review':case'review_limitations':return <><p style={muted}>Assessment results are exploratory. They should be combined with academic evidence, actual experiences, pathway research and qualified human guidance.</p><p><b>Recommended:</b> complete additional assessment families if a broader Career Intelligence profile is required.</p></>;
 default:return not;
 }
}

export default function CareerFullReportPage(){
 const [r,setR]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const u=auth.currentUser;if(!u)throw new Error('Please sign in.');const snap=await getDoc(doc(db,'users',u.uid));if(!snap.exists())throw new Error('Account not found.');const d=snap.data();if(d.careerReportAccess?.status!=='paid'&&d.institutionAccess?.status!=='active')throw new Error('Full Career Intelligence access is not active.');setR(normalise(d));}catch(e){setError(e.message||'Unable to load report.');}finally{setLoading(false);}})();},[]);
 if(loading)return <div style={{padding:80,textAlign:'center',fontWeight:800,color:'#64748b'}}>Preparing your 20-page Career Intelligence Report…</div>;
 if(error)return <div style={{maxWidth:700,margin:'60px auto',...card,textAlign:'center'}}><h2>Report unavailable</h2><p style={muted}>{error}</p></div>;
 const pages=getReportPages({tier:'full',pathway:r.pathway||'student'});
 return <div style={{background:'#f8fafc',minHeight:'100vh',padding:'28px 18px 70px'}}><style>{`@media print{body{background:#fff!important}.no-print{display:none!important}.report-page{break-before:page;min-height:94vh}}`}</style><div className="no-print" style={{maxWidth:1100,margin:'0 auto 15px',display:'flex',justifyContent:'space-between'}}><button onClick={()=>window.location.href='/dashboard/career'} style={{padding:'10px 14px',border:'1px solid #cbd5e1',background:'#fff',borderRadius:10,fontWeight:800}}>← Career Home</button><button onClick={()=>window.print()} style={{padding:'11px 16px',border:0,borderRadius:10,background:'#0f172a',color:'#fff',fontWeight:900}}>🖨 Save / Print PDF</button></div><main style={{maxWidth:1100,margin:'0 auto'}}><section style={{...card,background:'linear-gradient(135deg,#0f172a,#1e293b)',color:'#fff'}}><div style={{color:'#fbbf24',fontSize:11,fontWeight:900,letterSpacing:1.5}}>VIDYAVANTAGE · FULL CAREER INTELLIGENCE</div><h1 style={{fontSize:34,margin:'9px 0'}}>{r.profile?.name||'Your'} Career Intelligence Report</h1><p style={{color:'#cbd5e1',lineHeight:1.7}}>20-section integrated report architecture · evidence-conscious · no invented psychometric results</p></section><section style={{...card,marginTop:16,background:'#fffbeb'}}><b>{r.legacyAssessment?'Earlier assessment detected':'Integrated assessment bundle'}</b><p style={{...muted,marginBottom:0}}>{r.legacyAssessment?'This account was created with the earlier RIASEC-only assessment. The new report structure is active, but additional modules are marked Not assessed rather than being fabricated.':'Your selected assessment families are combined into one integrated Career Intelligence report.'}</p></section>{pages.map((p,n)=><section className="report-page" key={p.id} style={{...card,marginTop:16,minHeight:620}}><div style={{fontSize:11,fontWeight:900,letterSpacing:1.4,color:'#4f46e5'}}>{String(n+1).padStart(2,'0')} / {pages.length}</div><h2 style={{margin:'7px 0 16px',fontSize:27,color:'#0f172a'}}>{p.title}</h2><Content id={p.id} r={r}/></section>)}</main></div>;
}
