import React,{useEffect,useMemo,useState} from 'react';
import {auth} from './firebase';
import {PATHWAYS,PROFESSIONAL_INTENTS,STUDENT_STAGES,calculateAge,ageBandFor} from './career/careerAssessmentBlueprint';
import {getBundleByFamilies,getDefaultBundle,getItemsForBundle} from './career/assessmentSelection';
import {TEST_FAMILIES} from './career/testBundleCatalogue';

const input={width:'100%',padding:'12px 13px',border:'1px solid #dbe3ef',borderRadius:11,fontSize:14,background:'#fff'};
const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:22,boxShadow:'0 7px 25px rgba(15,23,42,.05)'};
const scale=['Strongly disagree','Disagree','Neither agree nor disagree','Agree','Strongly agree'];
const familyOrder=['interest','personality','aptitude_skills','work_values','learning'];
const familyColor={interest:'#4f46e5',personality:'#7c3aed',aptitude_skills:'#0369a1',work_values:'#047857',learning:'#b45309'};

function Field({label,children,hint}){return <label style={{display:'grid',gap:7,fontSize:13,fontWeight:800,color:'#334155'}}><span>{label}{hint&&<small style={{marginLeft:6,color:'#94a3b8'}}>{hint}</small>}</span>{children}</label>}
function titleFor(pathway){return pathway===PATHWAYS.PROFESSIONAL?'Professional Career Intelligence':pathway===PATHWAYS.HR?'HR Role Alignment':'Student Career Intelligence'}
function contextFields(pathway,intake,setIntake){
 const set=(k,v)=>setIntake(x=>({...x,[k]:v}));
 return <div style={card}>
  <div style={{color:'#4f46e5',fontSize:11,fontWeight:900,letterSpacing:1.3}}>PHASE 1 · CAREER CONTEXT</div>
  <h2 style={{margin:'6px 0',fontSize:25}}>Start with the person, not the test</h2>
  <p style={{color:'#64748b',lineHeight:1.65,fontSize:14}}>This context is collected for interpretation. It does not silently add another paid psychometric test.</p>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>
   <Field label="Date of Birth"><input type="date" style={input} value={intake.dob} onChange={e=>set('dob',e.target.value)} /></Field>
   <Field label="Age"><input style={{...input,background:'#f8fafc'}} readOnly value={intake.age||'Calculated from DOB'} /></Field>
   {pathway===PATHWAYS.STUDENT&&<>
    <Field label="Education stage"><select style={input} value={intake.educationStage} onChange={e=>set('educationStage',e.target.value)}><option value="">Select</option>{STUDENT_STAGES.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field>
    <Field label="Board / curriculum"><input style={input} value={intake.board} onChange={e=>set('board',e.target.value)} placeholder="CBSE, ICSE, State Board, PUC, IB…" /></Field>
    <Field label="Current class / year"><input style={input} value={intake.className} onChange={e=>set('className',e.target.value)} /></Field>
    <Field label="Current stream / combination"><input style={input} value={intake.stream} onChange={e=>set('stream',e.target.value)} /></Field>
    <Field label="Recent academic average / CGPA"><input style={input} value={intake.academicAverage} onChange={e=>set('academicAverage',e.target.value)} /></Field>
    <Field label="School / college"><input style={input} value={intake.institutionName} onChange={e=>set('institutionName',e.target.value)} /></Field>
    <Field label="Subjects you enjoy"><input style={input} value={intake.likedSubjects} onChange={e=>set('likedSubjects',e.target.value)} placeholder="Mathematics, Psychology, Biology…" /></Field>
    <Field label="Subjects you dislike / find difficult"><input style={input} value={intake.dislikedSubjects} onChange={e=>set('dislikedSubjects',e.target.value)} /></Field>
    <Field label="Hobbies / interests"><textarea style={{...input,minHeight:85}} value={intake.hobbies} onChange={e=>set('hobbies',e.target.value)} /></Field>
    <Field label="What do you want help with?"><textarea style={{...input,minHeight:85}} value={intake.goal} onChange={e=>set('goal',e.target.value)} placeholder="Stream choice, college, career ideas, changing course…" /></Field>
   </>}
   {pathway===PATHWAYS.PROFESSIONAL&&<>
    <Field label="Current role"><input style={input} value={intake.currentRole} onChange={e=>set('currentRole',e.target.value)} /></Field>
    <Field label="Current employer"><input style={input} value={intake.employer} onChange={e=>set('employer',e.target.value)} /></Field>
    <Field label="Years of experience"><input style={input} value={intake.experienceYears} onChange={e=>set('experienceYears',e.target.value)} /></Field>
    <Field label="Highest qualification"><input style={input} value={intake.qualification} onChange={e=>set('qualification',e.target.value)} /></Field>
    <Field label="Actual daily responsibilities"><textarea style={{...input,minHeight:90}} value={intake.dailyDuties} onChange={e=>set('dailyDuties',e.target.value)} /></Field>
    <Field label="Current skills"><textarea style={{...input,minHeight:90}} value={intake.skills} onChange={e=>set('skills',e.target.value)} /></Field>
    <Field label="Primary career intention"><select style={input} value={intake.professionalIntent} onChange={e=>set('professionalIntent',e.target.value)}><option value="">Select</option>{PROFESSIONAL_INTENTS.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field>
    <Field label="What would you like to move toward?"><textarea style={{...input,minHeight:90}} value={intake.targetDirection} onChange={e=>set('targetDirection',e.target.value)} /></Field>
   </>}
   {pathway===PATHWAYS.HR&&<>
    <Field label="Current role / designation"><input style={input} value={intake.currentRole} onChange={e=>set('currentRole',e.target.value)} /></Field>
    <Field label="Employer / organisation"><input style={input} value={intake.employer} onChange={e=>set('employer',e.target.value)} /></Field>
    <Field label="Target role"><input style={input} value={intake.targetRole} onChange={e=>set('targetRole',e.target.value)} /></Field>
    <Field label="Department / function"><input style={input} value={intake.department} onChange={e=>set('department',e.target.value)} /></Field>
    <Field label="Role responsibilities"><textarea style={{...input,minHeight:90}} value={intake.roleResponsibilities} onChange={e=>set('roleResponsibilities',e.target.value)} /></Field>
    <Field label="Technical competencies required"><textarea style={{...input,minHeight:90}} value={intake.roleTechnical} onChange={e=>set('roleTechnical',e.target.value)} /></Field>
    <Field label="Behavioural competencies required"><textarea style={{...input,minHeight:90}} value={intake.roleBehavioural} onChange={e=>set('roleBehavioural',e.target.value)} /></Field>
   </>}
  </div>
 </div>
}

export default function CareerAssessmentV3({onComplete,onUnlock}){
 const [pathway,setPathway]=useState(PATHWAYS.STUDENT);const [selected,setSelected]=useState(familyOrder);const [intake,setIntake]=useState({dob:'',age:'',educationStage:'',board:'',className:'',stream:'',academicAverage:'',institutionName:'',likedSubjects:'',dislikedSubjects:'',hobbies:'',goal:'',currentRole:'',employer:'',experienceYears:'',qualification:'',dailyDuties:'',skills:'',professionalIntent:'',targetDirection:'',targetRole:'',department:'',roleResponsibilities:'',roleTechnical:'',roleBehavioural:'',licenseCode:''});
 const [started,setStarted]=useState(false);const [answers,setAnswers]=useState({});const [page,setPage]=useState(0);const [report,setReport]=useState(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('vv_assessment_v3_progress')||'null');if(s){setPathway(s.pathway||PATHWAYS.STUDENT);setSelected(s.selected||familyOrder);setIntake(s.intake||intake);setAnswers(s.answers||{});setPage(Number(s.page)||0);setStarted(Boolean(s.started));}}catch(_){}},[]);
 useEffect(()=>{try{localStorage.setItem('vv_assessment_v3_progress',JSON.stringify({pathway,selected,intake,answers,page,started}));}catch(_){}},[pathway,selected,intake,answers,page,started]);
 const bundle=useMemo(()=>getBundleByFamilies(selected)||getDefaultBundle(),[selected]);
 const items=useMemo(()=>getItemsForBundle(bundle.id),[bundle.id]);
 const pageSize=6;const totalPages=Math.max(1,Math.ceil(items.length/pageSize));const currentItems=items.slice(page*pageSize,(page+1)*pageSize);const answered=items.filter(x=>answers[x.id]!==undefined).length;const progress=items.length?Math.round(answered/items.length*100):0;
 const toggleFamily=id=>{setSelected(s=>{const next=s.includes(id)?s.filter(x=>x!==id):[...s,id];return next.length?familyOrder.filter(x=>next.includes(x)):s;});setAnswers({});setPage(0);};
 const begin=()=>{setError('');const age=calculateAge(intake.dob);if(age==null||age<13){setError('Please enter a valid Date of Birth. VidyaVantage is currently available from age 13.');return;}setIntake(x=>({...x,age,ageBand:ageBandFor(age)}));try{localStorage.setItem('vv_selected_bundle_id',bundle.id);}catch(_){}setStarted(true);setPage(0);};
 const submit=async()=>{setSaving(true);setError('');try{const user=auth.currentUser;if(!user)throw new Error('Please sign in before submitting.');const token=await user.getIdToken();const r=await fetch('/api/career/submit-v2',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({pathway,intake,answers,bundleId:bundle.id,reportTier:'free'})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to save assessment.');try{localStorage.removeItem('vv_assessment_v3_progress');localStorage.setItem('vv_selected_bundle_id',bundle.id);}catch(_){}setReport(d.report);onComplete?.(d.report);}catch(e){setError(e.message||'Unable to save assessment.');}finally{setSaving(false);}};
 if(report)return <div style={{...card,maxWidth:1050,margin:'20px auto'}}><div style={{color:'#4f46e5',fontWeight:900,fontSize:11,letterSpacing:1.3}}>CAREER SNAPSHOT · 5 PAGES FREE</div><h1 style={{margin:'7px 0'}}>Your {bundle.title} result is ready</h1><p style={{color:'#64748b',lineHeight:1.7}}>This is an exploratory career-guidance result. It is not a diagnosis, IQ score, fixed identity or destiny.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'20px 0'}}>{selected.map(id=><div key={id} style={{padding:15,borderRadius:12,background:'#f8fafc'}}><strong>{TEST_FAMILIES[id].shortTitle}</strong><div style={{fontSize:13,color:'#64748b',marginTop:5}}>{TEST_FAMILIES[id].estimatedMinutes} min</div></div>)}</div><div style={{padding:18,background:'#eef2ff',borderRadius:13}}><strong>Premium unlock</strong><p style={{margin:'6px 0',color:'#475569'}}>Upgrade this same assessment to the full 20-page integrated Career Intelligence Report. You do not need to retake completed modules solely because you upgrade.</p><button onClick={()=>onUnlock?.(report)} style={{border:0,borderRadius:11,padding:'12px 18px',background:'#4f46e5',color:'#fff',fontWeight:900}}>View Premium Report</button></div></div>;
 return <div style={{maxWidth:1100,margin:'0 auto',paddingBottom:70}}>
  <div style={{...card,background:'linear-gradient(135deg,#0f172a,#1e293b)',color:'#fff',marginBottom:16}}><div style={{color:'#fbbf24',fontSize:11,fontWeight:900,letterSpacing:1.4}}>VIDYAVANTAGE · {titleFor(pathway).toUpperCase()}</div><h1 style={{margin:'8px 0 5px',fontSize:32}}>Build one assessment around the person.</h1><p style={{margin:0,color:'#cbd5e1',lineHeight:1.7}}>Choose the test families you need. Your career context is collected once, then the selected tests run as one continuous assessment and produce one integrated report.</p></div>
  {!started&&<>
   <div style={card}><div style={{fontSize:11,fontWeight:900,color:'#64748b',letterSpacing:1.2}}>WHO IS THIS FOR?</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{[[PATHWAYS.STUDENT,'Student'],[PATHWAYS.PROFESSIONAL,'Working Professional'],[PATHWAYS.HR,'HR / Employer']].map(([id,label])=><button key={id} onClick={()=>setPathway(id)} style={{padding:'10px 14px',borderRadius:10,border:'1px solid '+(pathway===id?'#4f46e5':'#dbe3ef'),background:pathway===id?'#eef2ff':'#fff',color:pathway===id?'#4338ca':'#475569',fontWeight:900}}>{label}</button>)}</div></div>
   <div style={{...card,marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',gap:15,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:11,fontWeight:900,color:'#4f46e5',letterSpacing:1.2}}>CHOOSE YOUR TESTS</div><h2 style={{margin:'5px 0'}}>Five independent assessment families</h2><p style={{margin:0,color:'#64748b'}}>Any non-empty combination is a valid bundle — 31 combinations in total.</p></div><div style={{padding:'9px 12px',background:'#f8fafc',borderRadius:10,fontWeight:900}}>{selected.length}/5 selected</div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:18}}>{familyOrder.map(id=>{const f=TEST_FAMILIES[id],on=selected.includes(id);return <button key={id} onClick={()=>toggleFamily(id)} style={{textAlign:'left',padding:16,borderRadius:14,border:'2px solid '+(on?familyColor[id]:'#e2e8f0'),background:on?'#fafafa':'#fff',cursor:'pointer'}}><div style={{fontSize:12,fontWeight:950,color:on?familyColor[id]:'#64748b'}}>{on?'SELECTED':'ADD TEST'}</div><h3 style={{margin:'6px 0',fontSize:17,color:'#0f172a'}}>{f.shortTitle}</h3><p style={{margin:'0 0 10px',fontSize:12,color:'#64748b',lineHeight:1.5}}>{f.description}</p><strong style={{fontSize:12}}>{f.durationMinutes.min}–{f.durationMinutes.max} min</strong></button>})}</div><div style={{marginTop:16,padding:15,background:'#f8fafc',borderRadius:12}}><strong>{bundle.title}</strong><div style={{fontSize:13,color:'#64748b',marginTop:4}}>Estimated {bundle.durationMinutes} minutes · one progress bar · one submission · one integrated 20-page premium report</div></div></div>
   {contextFields(pathway,intake,setIntake)}
   {error&&<div style={{marginTop:12,padding:13,background:'#fef2f2',color:'#991b1b',borderRadius:10,fontWeight:800}}>{error}</div>}
   <button onClick={begin} style={{marginTop:16,width:'100%',border:0,borderRadius:12,padding:15,background:'linear-gradient(135deg,#4f46e5,#7c3aed)',color:'#fff',fontWeight:950,fontSize:15}}>Start {bundle.title} →</button>
  </>}
  {started&&<div style={{marginTop:16}}><div style={{...card,position:'sticky',top:8,zIndex:2,marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><strong>{bundle.title}</strong><div style={{fontSize:12,color:'#64748b'}}>Career context + selected tests · save & resume</div></div><strong>{progress}%</strong></div><div style={{height:8,background:'#e2e8f0',borderRadius:99,marginTop:10}}><div style={{width:`${progress}%`,height:'100%',background:'#4f46e5',borderRadius:99}}/></div></div><div style={card}><div style={{fontSize:11,color:'#4f46e5',fontWeight:900,letterSpacing:1.2}}>PHASE 2 · {page+1} OF {totalPages}</div>{currentItems.map((item,i)=><div key={item.id} style={{padding:'18px 0',borderBottom:i===currentItems.length-1?'0':'1px solid #eef2f7'}}><div style={{fontWeight:850,color:'#0f172a',lineHeight:1.6}}>{page*pageSize+i+1}. {item.question}</div>{item.type==='objective'?<div style={{display:'grid',gap:8,marginTop:11}}>{item.options.map((o,idx)=><label key={o} style={{padding:11,border:'1px solid '+(answers[item.id]===idx?'#4f46e5':'#e2e8f0'),borderRadius:10,background:answers[item.id]===idx?'#eef2ff':'#fff'}}><input type="radio" name={item.id} checked={answers[item.id]===idx} onChange={()=>setAnswers(a=>({...a,[item.id]:idx}))}/> <span style={{marginLeft:7}}>{o}</span></label>)}</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:6,marginTop:11}}>{scale.map((o,idx)=><button key={o} onClick={()=>setAnswers(a=>({...a,[item.id]:idx+1}))} style={{minHeight:55,padding:6,border:'1px solid '+(answers[item.id]===idx+1?'#4f46e5':'#dbe3ef'),borderRadius:9,background:answers[item.id]===idx+1?'#eef2ff':'#fff',fontSize:11,fontWeight:750}}>{o}</button>)}</div>}</div>)}{error&&<div style={{marginTop:12,padding:12,background:'#fef2f2',color:'#991b1b',borderRadius:10,color:'#991b1b'}}>{error}</div>}<div style={{display:'flex',justifyContent:'space-between',gap:10,marginTop:18}}><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))} style={{padding:'11px 15px',borderRadius:10,border:'1px solid #dbe3ef',background:'#fff'}}>← Back</button>{page<totalPages-1?<button onClick={()=>setPage(p=>p+1)} style={{padding:'11px 15px',border:0,borderRadius:10,background:'#4f46e5',color:'#fff',fontWeight:900}}>Continue →</button>:<button disabled={saving||answered<items.length} onClick={submit} style={{padding:'11px 18px',border:0,borderRadius:10,background:answered<items.length?'#cbd5e1':'#4f46e5',color:'#fff',fontWeight:900}}>{saving?'Saving…':'Complete Assessment'}</button>}</div></div></div>}
 </div>;
}
